// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-duckduckgo",
 name: "Duckduckgo by Crawlora",
 description: "Public Duckduckgo data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_duckduckgo_search",description:"Use Crawlora to access public Duckduckgo data.",parameters:Type.Object({"q": Type.String({"description":"q parameter."}),"page": Type.Optional(Type.Integer({"description":"page parameter."})),"region": Type.Optional(Type.String({"description":"region parameter."})),"time_range": Type.Optional(Type.Union([Type.Literal("d"),Type.Literal("w"),Type.Literal("m"),Type.Literal("y")], {"description":"time_range parameter."})),"safe_search": Type.Optional(Type.Union([Type.Literal("strict"),Type.Literal("moderate"),Type.Literal("off")], {"description":"safe_search parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"duckduckgo-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-duckduckgo.");
 }
 return register(api);
};
export default plugin;
