// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-depop",
 name: "Depop by Crawlora",
 description: "Public Depop data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_depop_search",description:"Use Crawlora to access public Depop data.",parameters:Type.Object({"query": Type.String({"description":"query parameter."}),"price_min": Type.Optional(Type.Number({"description":"price_min parameter."})),"price_max": Type.Optional(Type.Number({"description":"price_max parameter."})),"condition": Type.Optional(Type.String({"description":"condition parameter."})),"colours": Type.Optional(Type.String({"description":"colours parameter."})),"on_sale": Type.Optional(Type.Boolean({"description":"on_sale parameter."})),"sort": Type.Optional(Type.String({"description":"sort parameter."})),"category": Type.Optional(Type.String({"description":"category parameter."})),"subcategory": Type.Optional(Type.String({"description":"subcategory parameter."})),"gender": Type.Optional(Type.String({"description":"gender parameter."})),"is_kids": Type.Optional(Type.Boolean({"description":"is_kids parameter."})),"brand_ids": Type.Optional(Type.String({"description":"brand_ids parameter."})),"sizes": Type.Optional(Type.String({"description":"sizes parameter."})),"after": Type.Optional(Type.String({"description":"after parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"depop-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-depop.");
 }
 return register(api);
};
export default plugin;
