// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-gdelt",
 name: "Gdelt by Crawlora",
 description: "Public Gdelt data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_gdelt_search",description:"Use Crawlora to access public Gdelt data.",parameters:Type.Object({"query": Type.String({"description":"query parameter."}),"country": Type.Optional(Type.String({"description":"country parameter."})),"language": Type.Optional(Type.String({"description":"language parameter."})),"domain": Type.Optional(Type.String({"description":"domain parameter."})),"timespan": Type.Optional(Type.String({"description":"timespan parameter."})),"from": Type.Optional(Type.String({"description":"from parameter."})),"to": Type.Optional(Type.String({"description":"to parameter."})),"sort": Type.Optional(Type.Union([Type.Literal("relevance"),Type.Literal("datedesc"),Type.Literal("dateasc"),Type.Literal("tonedesc"),Type.Literal("toneasc")], {"description":"sort parameter."})),"maxrecords": Type.Optional(Type.Integer({"description":"maxrecords parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"gdelt-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-gdelt.");
 }
 return register(api);
};
export default plugin;
