// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-zillow",
 name: "Zillow by Crawlora",
 description: "Zillow public property search through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_zillow_search",description:"Search public Zillow property listings.",parameters:Type.Object({"location": Type.String({"description":"City, ZIP code, or neighborhood."}),"page": Type.Optional(Type.Number({"description":"Page number.","minimum":1})),"status": Type.Optional(Type.Union([Type.Literal("for_sale"),Type.Literal("sale"),Type.Literal("for-sale"),Type.Literal("for_rent"),Type.Literal("rent"),Type.Literal("for-rent"),Type.Literal("sold")], {"description":"Listing status."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"zillow-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-zillow.");
 }
 return register(api);
};
export default plugin;
