// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-carmax",
 name: "Carmax by Crawlora",
 description: "Public Carmax data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_carmax_search",description:"Use Crawlora to access public Carmax data.",parameters:Type.Object({"make": Type.Optional(Type.String({"description":"make parameter."})),"model": Type.Optional(Type.String({"description":"model parameter."})),"zip": Type.Optional(Type.String({"description":"zip parameter."})),"sort": Type.Optional(Type.String({"description":"sort parameter."})),"min_year": Type.Optional(Type.Integer({"description":"min_year parameter."})),"max_year": Type.Optional(Type.Integer({"description":"max_year parameter."})),"min_price": Type.Optional(Type.Integer({"description":"min_price parameter."})),"max_price": Type.Optional(Type.Integer({"description":"max_price parameter."})),"max_mileage": Type.Optional(Type.Integer({"description":"max_mileage parameter."})),"page": Type.Optional(Type.Integer({"description":"page parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"carmax-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-carmax.");
 }
 return register(api);
};
export default plugin;
