// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-booking",
 name: "Booking.com by Crawlora",
 description: "Booking.com public accommodation search through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_booking_search",description:"Search public Booking.com accommodations.",parameters:Type.Object({"query": Type.String({"description":"Destination or property query."}),"checkin": Type.String({"description":"Check-in date (YYYY-MM-DD)."}),"checkout": Type.String({"description":"Check-out date (YYYY-MM-DD)."}),"adults": Type.Optional(Type.Number({"description":"Number of adults.","minimum":1})),"rooms": Type.Optional(Type.Number({"description":"Number of rooms.","minimum":1})),"children": Type.Optional(Type.Number({"description":"Number of children.","minimum":0})),"page": Type.Optional(Type.Number({"description":"Page number.","minimum":1}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"booking-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-booking.");
 }
 return register(api);
};
export default plugin;
