export const cases = [
 ['google_search', {q:'coffee & tea',num:10}, 'POST', '/google/search', {keyword:'coffee & tea',country:'us',language:'en',limit:10}],
 ['google_news', {q:'coffee',count:5}, 'GET', '/google/news?q=coffee&count=5'],
 ['google_videos', {q:'coffee',count:5}, 'GET', '/google/videos?q=coffee&count=5'],
 ['bing_search', {q:'coffee',count:5}, 'GET', '/bing/search?q=coffee&count=5'],
 ['amazon_search', {k:'coffee'}, 'GET', '/amazon/search?k=coffee'],
 ['amazon_product', {asin:'B0DGJ736JM'}, 'GET', '/amazon/product/B0DGJ736JM'],
 ['ebay_search', {q:'coffee'}, 'POST', '/ebay/search', {keyword:'coffee'}],
 ['youtube_transcript', {id:'dQw4w9WgXcQ'}, 'GET', '/youtube/transcript/dQw4w9WgXcQ'],
 ['yahoo_finance_ticker_quote', {ticker:'BRK-B'}, 'GET', '/yahoo-finance/ticker/BRK-B/quote'],
 ['sec_company_search', {q:'apple'}, 'GET', '/sec/company/search?q=apple'],
 ['sec_company_intelligence', {ticker:'AAPL'}, 'GET', '/sec/company/intelligence?ticker=AAPL'],
 ['sec_financials', {ticker:'AAPL',statement:'income',period:'annual',limit:5}, 'GET', '/sec/financials?ticker=AAPL&statement=income&period=annual&limit=5'],
 ['sec_filings', {ticker:'AAPL',form:'10-K',limit:5}, 'GET', '/sec/company/submissions?ticker=AAPL&form=10-K&limit=5'],
 ['sec_filing_sections', {accession:'0000320193-25-000079',ticker:'AAPL',items:'1A,7'}, 'GET', '/sec/filing/sections?accession=0000320193-25-000079&ticker=AAPL&items=1A%2C7'],
 ['sec_full_text_search', {q:'artificial intelligence',forms:'10-K'}, 'GET', '/sec/full-text-search?q=artificial+intelligence&forms=10-K'],
 ['sec_insider', {ticker:'AAPL',limit:5}, 'GET', '/sec/insider?ticker=AAPL&limit=5'],
 ['jobs_hiring_signals', {provider:'greenhouse',token:'stripe'}, 'GET', '/jobs/hiring-signals?provider=greenhouse&token=stripe'],
 ['jobs_company_search', {slug:'stripe'}, 'GET', '/jobs/company-search?slug=stripe'],
 ['jobs_greenhouse_board', {token:'stripe',content:true}, 'GET', '/jobs/greenhouse/board?token=stripe&content=true'],
 ['jobs_lever_postings', {company:'spotify'}, 'GET', '/jobs/lever/postings?company=spotify'],
 ['jobs_ashby_board', {org:'openai'}, 'GET', '/jobs/ashby/board?org=openai'],
 ['google_trends_explore', {q:'coffee'}, 'POST', '/google/trends/explore', {keywords:['coffee']}],
 ['google_map_search', {q:'coffee'}, 'POST', '/google/map/search', {keyword:'coffee'}],
 ['spotify_search', {q:'ambient focus',limit:10,offset:0}, 'GET', '/spotify/search?q=ambient+focus&limit=10&offset=0'],
 ['tiktok_post', {id:'7350000000000000000'}, 'GET', '/tiktok/post/7350000000000000000'],
 ['reddit_search', {q:'web scraping',subreddit:'programming',sort:'relevance',time:'week',limit:10}, 'GET', '/reddit/search?q=web+scraping&subreddit=programming&sort=relevance&time=week&limit=10'],
 ['github_search_repositories', {q:'browser automation',sort:'stars',order:'desc',page:1,per_page:10}, 'GET', '/github/search/repositories?q=browser+automation&sort=stars&order=desc&page=1&per_page=10'],
 ['pinterest_search', {query:'minimalist kitchen'}, 'GET', '/pinterest/search?query=minimalist+kitchen'],
 ['airbnb_search', {location:'Lisbon',check_in:'2026-10-10',check_out:'2026-10-12',adults:2,page:1,currency:'EUR'}, 'GET', '/airbnb/search?location=Lisbon&check_in=2026-10-10&check_out=2026-10-12&adults=2&page=1&currency=EUR'],
 ['booking_search', {query:'Tokyo',checkin:'2026-10-10',checkout:'2026-10-12',adults:2,rooms:1,children:0,page:1}, 'GET', '/booking/search?query=Tokyo&checkin=2026-10-10&checkout=2026-10-12&adults=2&rooms=1&children=0&page=1'],
 ['yelp_search', {term:'ramen',location:'San Francisco',limit:10,offset:0}, 'GET', '/yelp/search?term=ramen&location=San+Francisco&limit=10&offset=0'],
 ['zillow_search', {location:'Austin, TX',page:1,status:'for_sale'}, 'GET', '/zillow/search?location=Austin%2C+TX&page=1&status=for_sale'],
 ['imdb_search', {query:'science fiction',limit:10}, 'GET', '/imdb/search?query=science+fiction&limit=10'],
 ['steam_app', {appid:'440',cc:'us',l:'en'}, 'GET', '/steam/app?appid=440&cc=us&l=en'],
 ['coingecko_markets', {vs_currency:'usd',page:1,limit:10}, 'GET', '/coingecko/markets?vs_currency=usd&page=1&limit=10'],
 ['polymarket_events', {limit:10,offset:0,order:'volume24hr',ascending:false,closed:'false'}, 'GET', '/polymarket/events?limit=10&offset=0&order=volume24hr&ascending=false&closed=false'],
 ['kalshi_events', {limit:10,status:'open',with_nested_markets:true}, 'GET', '/kalshi/events?limit=10&status=open&with_nested_markets=true'],
 ['apple_books_search', {term:'machine learning',country:'us',lang:'en',limit:10,page:1}, 'GET', '/apple-books/search?term=machine+learning&country=us&lang=en&limit=10&page=1'],
 ['apple_jobs_search', {q:'machine learning',location:'Austin',page:1}, 'GET', '/apple-jobs/search?q=machine+learning&location=Austin&page=1'],
 ['opensea_collection', {slug:'boredapeyachtclub'}, 'GET', '/opensea/collection/boredapeyachtclub'],
];
