export const cases = [
 ['google_search', {q:'coffee & tea',num:10}, 'POST', '/google/search', {keyword:'coffee & tea',country:'us',language:'en',limit:10}],
 ['google_news', {q:'coffee',count:5}, 'GET', '/google/news?q=coffee&count=5'],
 ['google_videos', {q:'coffee',count:5}, 'GET', '/google/videos?q=coffee&count=5'],
 ['bing_search', {q:'coffee',count:5}, 'GET', '/bing/search?q=coffee&count=5'],
 ['amazon_search', {k:'coffee'}, 'GET', '/amazon/search?k=coffee'],
 ['amazon_product', {asin:'B0DGJ736JM'}, 'GET', '/amazon/product/B0DGJ736JM'],
 ['ebay_search', {q:'coffee'}, 'POST', '/ebay/search', {keyword:'coffee'}],
 ['youtube_transcript', {id:'dQw4w9WgXcQ'}, 'GET', '/youtube/transcript/dQw4w9WgXcQ'],
 ['yahoo_finance_ticker_quote', {ticker:'BRK-B'}, 'GET', '/yahoo-finance/ticker/BRK-B/quote'],
 ['sec_company_search', {q:'apple'}, 'GET', '/sec/company/search?q=apple'],
 ['sec_company_intelligence', {ticker:'AAPL'}, 'GET', '/sec/company/intelligence?ticker=AAPL'],
 ['sec_financials', {ticker:'AAPL',statement:'income',period:'annual',limit:5}, 'GET', '/sec/financials?ticker=AAPL&statement=income&period=annual&limit=5'],
 ['sec_filings', {ticker:'AAPL',form:'10-K',limit:5}, 'GET', '/sec/company/submissions?ticker=AAPL&form=10-K&limit=5'],
 ['sec_filing_sections', {accession:'0000320193-25-000079',ticker:'AAPL',items:'1A,7'}, 'GET', '/sec/filing/sections?accession=0000320193-25-000079&ticker=AAPL&items=1A%2C7'],
 ['sec_full_text_search', {q:'artificial intelligence',forms:'10-K'}, 'GET', '/sec/full-text-search?q=artificial+intelligence&forms=10-K'],
 ['sec_insider', {ticker:'AAPL',limit:5}, 'GET', '/sec/insider?ticker=AAPL&limit=5'],
 ['jobs_hiring_signals', {provider:'greenhouse',token:'stripe'}, 'GET', '/jobs/hiring-signals?provider=greenhouse&token=stripe'],
 ['jobs_company_search', {slug:'stripe'}, 'GET', '/jobs/company-search?slug=stripe'],
 ['jobs_greenhouse_board', {token:'stripe',content:true}, 'GET', '/jobs/greenhouse/board?token=stripe&content=true'],
 ['jobs_lever_postings', {company:'spotify'}, 'GET', '/jobs/lever/postings?company=spotify'],
 ['jobs_ashby_board', {org:'openai'}, 'GET', '/jobs/ashby/board?org=openai'],
 ['google_trends_explore', {q:'coffee'}, 'POST', '/google/trends/explore', {keywords:['coffee']}],
 ['google_map_search', {q:'coffee'}, 'POST', '/google/map/search', {keyword:'coffee'}],
];
