// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-opentable",
 name: "Opentable by Crawlora",
 description: "Public Opentable data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_opentable_restaurant",description:"Use Crawlora to access public Opentable data.",parameters:Type.Object({"restaurant_id": Type.String({"description":"restaurant_id parameter."}),"date_time": Type.Optional(Type.String({"description":"date_time parameter."})),"party_size": Type.Optional(Type.Integer({"description":"party_size parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"opentable-restaurant",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-opentable.");
 }
 return register(api);
};
export default plugin;
