// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-burgerking",
 name: "Burgerking by Crawlora",
 description: "Public Burgerking data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_burgerking_product",description:"Use Crawlora to access public Burgerking data.",parameters:Type.Object({"store_id": Type.String({"description":"store_id parameter."}),"item_id": Type.String({"description":"item_id parameter."}),"market": Type.Optional(Type.String({"description":"market parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"burgerking-product",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-burgerking.");
 }
 return register(api);
};
export default plugin;
