// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-polymarket",
 name: "Polymarket by Crawlora",
 description: "Polymarket public event data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_polymarket_events",description:"List public Polymarket prediction events.",parameters:Type.Object({"limit": Type.Optional(Type.Number({"description":"Maximum events.","minimum":1,"maximum":100})),"offset": Type.Optional(Type.Number({"description":"Result offset.","minimum":0})),"order": Type.Optional(Type.Union([Type.Literal("volume24hr"),Type.Literal("volume"),Type.Literal("liquidity"),Type.Literal("endDate"),Type.Literal("updatedAt"),Type.Literal("createdAt"),Type.Literal("id"),Type.Literal("slug"),Type.Literal("title"),Type.Literal("question"),Type.Literal("label")], {"description":"Sort field."})),"ascending": Type.Optional(Type.Boolean({"description":"Sort ascending."})),"closed": Type.Optional(Type.Union([Type.Literal("true"),Type.Literal("false")], {"description":"Filter closed events."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"polymarket-events",params);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-polymarket.");
 }
 return register(api);
};
export default plugin;
