// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-manga",
 name: "Manga by Crawlora",
 description: "Public Manga data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_manga_search",description:"Use Crawlora to access public Manga data.",parameters:Type.Object({"query": Type.String({"description":"query parameter."}),"sort": Type.Optional(Type.Union([Type.Literal("SEARCH_MATCH"),Type.Literal("POPULARITY_DESC"),Type.Literal("SCORE_DESC"),Type.Literal("TRENDING_DESC"),Type.Literal("FAVOURITES_DESC"),Type.Literal("START_DATE_DESC")], {"description":"sort parameter."})),"page": Type.Optional(Type.Integer({"description":"page parameter."})),"per_page": Type.Optional(Type.Integer({"description":"per_page parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"manga-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-manga.");
 }
 return register(api);
};
export default plugin;
