// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-lazada",
 name: "Lazada by Crawlora",
 description: "Public Lazada data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_lazada_search",description:"Use Crawlora to access public Lazada data.",parameters:Type.Object({"country": Type.Optional(Type.Union([Type.Literal("id"),Type.Literal("ph"),Type.Literal("th"),Type.Literal("my"),Type.Literal("vn"),Type.Literal("sg")], {"description":"country parameter."})),"q": Type.String({"description":"q parameter."}),"page": Type.Optional(Type.Integer({"description":"page parameter."})),"sort": Type.Optional(Type.Union([Type.Literal("popularity"),Type.Literal("priceasc"),Type.Literal("pricedesc")], {"description":"sort parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"lazada-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-lazada.");
 }
 return register(api);
};
export default plugin;
