// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-tripadvisor",
 name: "Tripadvisor by Crawlora",
 description: "Public Tripadvisor data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_tripadvisor_search",description:"Use Crawlora to access public Tripadvisor data.",parameters:Type.Object({"geo_id": Type.Integer({"description":"geo_id parameter."}),"type": Type.String({"description":"type parameter."}),"filter_id": Type.Optional(Type.String({"description":"filter_id parameter."})),"class": Type.Optional(Type.Integer({"description":"class parameter."})),"amenities": Type.Optional(Type.String({"description":"amenities parameter."})),"price_min": Type.Optional(Type.Integer({"description":"price_min parameter."})),"price_max": Type.Optional(Type.Integer({"description":"price_max parameter."})),"pricing_mode": Type.Optional(Type.String({"description":"pricing_mode parameter."})),"travelers_choice": Type.Optional(Type.Boolean({"description":"travelers_choice parameter."})),"travelers_choice_botb": Type.Optional(Type.Boolean({"description":"travelers_choice_botb parameter."})),"restaurant_date": Type.Optional(Type.String({"description":"restaurant_date parameter."})),"restaurant_time": Type.Optional(Type.String({"description":"restaurant_time parameter."})),"restaurant_guests": Type.Optional(Type.Integer({"description":"restaurant_guests parameter."})),"establishment_types": Type.Optional(Type.String({"description":"establishment_types parameter."})),"online_options": Type.Optional(Type.String({"description":"online_options parameter."})),"offset": Type.Optional(Type.Integer({"description":"offset parameter."})),"limit": Type.Optional(Type.Integer({"description":"limit parameter."})),"locale": Type.Optional(Type.String({"description":"locale parameter."})),"currency": Type.Optional(Type.String({"description":"currency parameter."})),"sort": Type.Optional(Type.String({"description":"sort parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"tripadvisor-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-tripadvisor.");
 }
 return register(api);
};
export default plugin;
