// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-lever",
 name: "Lever by Crawlora",
 description: "Public Lever job postings through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({
      name: "crawlora_jobs_lever_postings",
      description: "List a company's public Lever job postings, normalized.",
      parameters: Type.Object({
        company: Type.String({ description: "Lever company slug, e.g. spotify." })
      }),
      async execute(params, config, context) {
        return callCrawlora(config, context.signal, "jobs-lever-postings", params);
      }
    })],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-lever.");
 }
 return register(api);
};
export default plugin;
