// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-redfin",
 name: "Redfin by Crawlora",
 description: "Public Redfin data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_redfin_property",description:"Use Crawlora to access public Redfin data.",parameters:Type.Object({"url": Type.Optional(Type.String({"description":"url parameter."})),"property_id": Type.Optional(Type.String({"description":"property_id parameter."})),"listing_id": Type.Optional(Type.String({"description":"listing_id parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"redfin-property",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-redfin.");
 }
 return register(api);
};
export default plugin;
