// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-airbnb",
 name: "Airbnb by Crawlora",
 description: "Airbnb public listing search through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_airbnb_search",description:"Search public Airbnb listings by location.",parameters:Type.Object({"location": Type.String({"description":"City, region, or neighborhood."}),"check_in": Type.Optional(Type.String({"description":"Check-in date (YYYY-MM-DD)."})),"check_out": Type.Optional(Type.String({"description":"Check-out date (YYYY-MM-DD)."})),"adults": Type.Optional(Type.Number({"description":"Number of adults.","minimum":1})),"page": Type.Optional(Type.Number({"description":"Page number.","minimum":1})),"currency": Type.Optional(Type.String({"description":"Currency code."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"airbnb-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-airbnb.");
 }
 return register(api);
};
export default plugin;
