// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-walgreens",
 name: "Walgreens by Crawlora",
 description: "Public Walgreens data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_walgreens_stores",description:"Use Crawlora to access public Walgreens data.",parameters:Type.Object({"latitude": Type.Optional(Type.Number({"description":"latitude parameter."})),"longitude": Type.Optional(Type.Number({"description":"longitude parameter."})),"zip": Type.Optional(Type.String({"description":"zip parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"walgreens-stores",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-walgreens.");
 }
 return register(api);
};
export default plugin;
