// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-walmart",
 name: "Walmart by Crawlora",
 description: "Public Walmart data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_walmart_search",description:"Use Crawlora to access public Walmart data.",parameters:Type.Object({"q": Type.String({"description":"q parameter."}),"page": Type.Optional(Type.Integer({"description":"page parameter."})),"sort": Type.Optional(Type.Union([Type.Literal("best_match"),Type.Literal("price_low"),Type.Literal("price_high"),Type.Literal("best_seller"),Type.Literal("new_arrivals"),Type.Literal("rating_high")], {"description":"sort parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"walmart-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-walmart.");
 }
 return register(api);
};
export default plugin;
