// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-tesla-jobs",
 name: "Tesla Jobs by Crawlora",
 description: "Public Tesla Jobs data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_tesla_jobs_list",description:"Use Crawlora to access public Tesla Jobs data.",parameters:Type.Object({"query": Type.Optional(Type.String({"description":"query parameter."})),"location": Type.Optional(Type.String({"description":"location parameter."})),"page": Type.Optional(Type.Integer({"description":"page parameter."})),"page_size": Type.Optional(Type.Integer({"description":"page_size parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"tesla-jobs-list",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-tesla-jobs.");
 }
 return register(api);
};
export default plugin;
