// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-facebook",
 name: "Facebook by Crawlora",
 description: "Public Facebook data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_facebook_marketplace_search",description:"Use Crawlora to access public Facebook data.",parameters:Type.Object({"location": Type.String({"description":"location parameter."}),"query": Type.Optional(Type.String({"description":"query parameter."})),"category": Type.Optional(Type.Union([Type.Literal("vehicles"),Type.Literal("property_rentals"),Type.Literal("classifieds"),Type.Literal("apparel"),Type.Literal("electronics"),Type.Literal("entertainment"),Type.Literal("family"),Type.Literal("free"),Type.Literal("garden_outdoors"),Type.Literal("hobbies"),Type.Literal("home_goods"),Type.Literal("home_improvement"),Type.Literal("musical_instruments"),Type.Literal("office_supplies"),Type.Literal("pet_supplies"),Type.Literal("property_sale"),Type.Literal("sporting_goods"),Type.Literal("toys_games")], {"description":"category parameter."})),"min_price": Type.Optional(Type.Integer({"description":"min_price parameter."})),"max_price": Type.Optional(Type.Integer({"description":"max_price parameter."})),"sort_by": Type.Optional(Type.Union([Type.Literal("best_match"),Type.Literal("distance_ascend"),Type.Literal("creation_time_descend"),Type.Literal("price_ascend"),Type.Literal("price_descend")], {"description":"sort_by parameter."})),"days_since_listed": Type.Optional(Type.Union([Type.Literal("1"),Type.Literal("7"),Type.Literal("30")], {"description":"days_since_listed parameter."})),"condition": Type.Optional(Type.Union([Type.Literal("new"),Type.Literal("used_like_new"),Type.Literal("used_good"),Type.Literal("used_fair")], {"description":"condition parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"facebook-marketplace-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-facebook.");
 }
 return register(api);
};
export default plugin;
