// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-tes-job",
 name: "Tes Job by Crawlora",
 description: "Public Tes Job data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_tes_job_search",description:"Use Crawlora to access public Tes Job data.",parameters:Type.Object({"keywords": Type.Optional(Type.String({"description":"keywords parameter."})),"location": Type.Optional(Type.String({"description":"location parameter."})),"radius_miles": Type.Optional(Type.Union([Type.Literal("3"),Type.Literal("5"),Type.Literal("10"),Type.Literal("15"),Type.Literal("20"),Type.Literal("30"),Type.Literal("50"),Type.Literal("70"),Type.Literal("100"),Type.Literal("500")], {"description":"radius_miles parameter."})),"page": Type.Optional(Type.Integer({"description":"page parameter."})),"page_size": Type.Optional(Type.Integer({"description":"page_size parameter."})),"sort": Type.Optional(Type.Union([Type.Literal("relevance"),Type.Literal("newest"),Type.Literal("distance")], {"description":"sort parameter."})),"contract_type": Type.Optional(Type.Union([Type.Literal("Full Time"),Type.Literal("Part Time")], {"description":"contract_type parameter."})),"contract_term": Type.Optional(Type.Union([Type.Literal("Permanent"),Type.Literal("Fixed Term"),Type.Literal("Casual"),Type.Literal("Maternity Cover"),Type.Literal("Temporary"),Type.Literal("Supply")], {"description":"contract_term parameter."})),"position": Type.Optional(Type.String({"description":"position parameter."})),"subject": Type.Optional(Type.String({"description":"subject parameter."})),"workplace": Type.Optional(Type.String({"description":"workplace parameter."})),"salary_min": Type.Optional(Type.Integer({"description":"salary_min parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"tes-job-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-tes-job.");
 }
 return register(api);
};
export default plugin;
