// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-coingecko",
 name: "CoinGecko by Crawlora",
 description: "CoinGecko public market data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_coingecko_markets",description:"Fetch public cryptocurrency market rankings.",parameters:Type.Object({"vs_currency": Type.String({"description":"Quote currency, such as usd or eur."}),"page": Type.Optional(Type.Number({"description":"Page number.","minimum":1})),"limit": Type.Optional(Type.Number({"description":"Markets per page.","minimum":1,"maximum":250}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"coingecko-markets",params);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-coingecko.");
 }
 return register(api);
};
export default plugin;
