// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-jimmy-johns",
 name: "Jimmy Johns by Crawlora",
 description: "Public Jimmy Johns data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_jimmy_johns_nearby",description:"Use Crawlora to access public Jimmy Johns data.",parameters:Type.Object({"latitude": Type.Number({"description":"latitude parameter."}),"longitude": Type.Number({"description":"longitude parameter."}),"radius": Type.Optional(Type.Integer({"description":"radius parameter."})),"limit": Type.Optional(Type.Integer({"description":"limit parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"jimmy-johns-nearby",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-jimmy-johns.");
 }
 return register(api);
};
export default plugin;
