// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-jcrew",
 name: "Jcrew by Crawlora",
 description: "Public Jcrew data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_jcrew_product",description:"Use Crawlora to access public Jcrew data.",parameters:Type.Object({"pid": Type.String({"description":"pid parameter."}),"site": Type.Optional(Type.Union([Type.Literal("jcrew"),Type.Literal("factory")], {"description":"site parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"jcrew-product",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-jcrew.");
 }
 return register(api);
};
export default plugin;
