// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-mcdonalds",
 name: "Mcdonalds by Crawlora",
 description: "Public Mcdonalds data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_mcdonalds_item",description:"Use Crawlora to access public Mcdonalds data.",parameters:Type.Object({"item_id": Type.String({"description":"item_id parameter."}),"country": Type.Optional(Type.Union([Type.Literal("us"),Type.Literal("ca"),Type.Literal("au"),Type.Literal("ie"),Type.Literal("nz"),Type.Literal("ch"),Type.Literal("se")], {"description":"country parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"mcdonalds-item",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-mcdonalds.");
 }
 return register(api);
};
export default plugin;
