// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-yelp",
 name: "Yelp by Crawlora",
 description: "Yelp public business search through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_yelp_search",description:"Search public Yelp businesses.",parameters:Type.Object({"term": Type.String({"description":"Business or service query."}),"location": Type.String({"description":"City, address, or region."}),"limit": Type.Optional(Type.Number({"description":"Maximum businesses.","minimum":1,"maximum":50})),"offset": Type.Optional(Type.Number({"description":"Result offset.","minimum":0}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"yelp-search",params);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-yelp.");
 }
 return register(api);
};
export default plugin;
