// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-audible",
 name: "Audible by Crawlora",
 description: "Public Audible data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_audible_search",description:"Use Crawlora to access public Audible data.",parameters:Type.Object({"q": Type.Optional(Type.String({"description":"q parameter."})),"title": Type.Optional(Type.String({"description":"title parameter."})),"author": Type.Optional(Type.String({"description":"author parameter."})),"narrator": Type.Optional(Type.String({"description":"narrator parameter."})),"category_id": Type.Optional(Type.String({"description":"category_id parameter."})),"page": Type.Optional(Type.Integer({"description":"page parameter."})),"limit": Type.Optional(Type.Integer({"description":"limit parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"audible-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-audible.");
 }
 return register(api);
};
export default plugin;
