// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-greenhouse",
 name: "Greenhouse by Crawlora",
 description: "Public Greenhouse job-board listings through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({
      name: "crawlora_jobs_greenhouse_board",
      description: "List a company's public Greenhouse job board postings, normalized to a shared Job shape.",
      parameters: Type.Object({
        token: Type.String({ description: "Greenhouse board token (careers URL slug), e.g. stripe." }),
        content: Type.Optional(Type.Boolean({ description: "Include full HTML description per job." }))
      }),
      async execute(params, config, context) {
        return callCrawlora(config, context.signal, "jobs-greenhouse-board", params);
      }
    })],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-greenhouse.");
 }
 return register(api);
};
export default plugin;
