// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-bonhams",
 name: "Bonhams by Crawlora",
 description: "Public Bonhams data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_bonhams_auction_search",description:"Use Crawlora to access public Bonhams data.",parameters:Type.Object({"q": Type.Optional(Type.String({"description":"q parameter."})),"country": Type.Optional(Type.String({"description":"country parameter."})),"category": Type.Optional(Type.String({"description":"category parameter."})),"month": Type.Optional(Type.String({"description":"month parameter."})),"auction_type": Type.Optional(Type.Union([Type.Literal("ONLINE"),Type.Literal("PUBLIC"),Type.Literal("EXHIBITION"),Type.Literal("OTHER")], {"description":"auction_type parameter."})),"status": Type.Optional(Type.Union([Type.Literal("upcoming"),Type.Literal("past"),Type.Literal("all")], {"description":"status parameter."})),"page": Type.Optional(Type.Integer({"description":"page parameter."})),"per_page": Type.Optional(Type.Integer({"description":"per_page parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"bonhams-auction-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-bonhams.");
 }
 return register(api);
};
export default plugin;
