// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-ashby",
 name: "Ashby by Crawlora",
 description: "Public Ashby job-board listings through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({
      name: "crawlora_jobs_ashby_board",
      description: "List an organization's public Ashby job board postings, normalized.",
      parameters: Type.Object({
        org: Type.String({ description: "Ashby org slug, e.g. openai." })
      }),
      async execute(params, config, context) {
        return callCrawlora(config, context.signal, "jobs-ashby-board", params);
      }
    })],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-ashby.");
 }
 return register(api);
};
export default plugin;
