// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-kroger",
 name: "Kroger by Crawlora",
 description: "Public Kroger data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_kroger_search",description:"Use Crawlora to access public Kroger data.",parameters:Type.Object({"query": Type.String({"description":"query parameter."}),"page": Type.Optional(Type.Integer({"description":"page parameter."})),"sort": Type.Optional(Type.Union([Type.Literal("relevance"),Type.Literal("name_asc"),Type.Literal("popularity_desc")], {"description":"sort parameter."})),"brands": Type.Optional(Type.String({"description":"brands parameter."})),"nutrition": Type.Optional(Type.String({"description":"nutrition parameter."})),"flavor": Type.Optional(Type.String({"description":"flavor parameter."})),"scent": Type.Optional(Type.String({"description":"scent parameter."})),"savings": Type.Optional(Type.String({"description":"savings parameter."})),"more_options": Type.Optional(Type.String({"description":"more_options parameter."})),"price_min": Type.Optional(Type.Number({"description":"price_min parameter."})),"price_max": Type.Optional(Type.Number({"description":"price_max parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"kroger-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-kroger.");
 }
 return register(api);
};
export default plugin;
