// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-apple-jobs",
 name: "Apple Jobs by Crawlora",
 description: "Apple public job search through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_apple_jobs_search",description:"Search public Apple job openings.",parameters:Type.Object({"q": Type.String({"description":"Role or keyword query."}),"location": Type.Optional(Type.String({"description":"Location filter."})),"page": Type.Optional(Type.Number({"description":"Page number.","minimum":1}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"apple-jobs-search",params);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-apple-jobs.");
 }
 return register(api);
};
export default plugin;
