// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-instacart",
 name: "Instacart by Crawlora",
 description: "Public Instacart data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_instacart_search",description:"Use Crawlora to access public Instacart data.",parameters:Type.Object({"shop_id": Type.String({"description":"shop_id parameter."}),"store_slug": Type.String({"description":"store_slug parameter."}),"q": Type.String({"description":"q parameter."})}),async execute(params,config,context){return callCrawlora(config,context.signal,"instacart-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-instacart.");
 }
 return register(api);
};
export default plugin;
