// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-justeat",
 name: "Justeat by Crawlora",
 description: "Public Justeat data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_justeat_search",description:"Use Crawlora to access public Justeat data.",parameters:Type.Object({"postcode": Type.String({"description":"postcode parameter."}),"limit": Type.Optional(Type.Integer({"description":"limit parameter."})),"filter": Type.Optional(Type.String({"description":"filter parameter."})),"sort_by": Type.Optional(Type.Union([Type.Literal("best_match"),Type.Literal("review_rating"),Type.Literal("distance"),Type.Literal("delivery_time"),Type.Literal("minimum_order_value"),Type.Literal("delivery_fee")], {"description":"sort_by parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"justeat-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-justeat.");
 }
 return register(api);
};
export default plugin;
