// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-zalando",
 name: "Zalando by Crawlora",
 description: "Public Zalando data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_zalando_search",description:"Use Crawlora to access public Zalando data.",parameters:Type.Object({"q": Type.String({"description":"q parameter."}),"market": Type.Union([Type.Literal("at"),Type.Literal("be"),Type.Literal("ch"),Type.Literal("cz"),Type.Literal("de"),Type.Literal("dk"),Type.Literal("ee"),Type.Literal("es"),Type.Literal("fi"),Type.Literal("fr"),Type.Literal("gb"),Type.Literal("hr"),Type.Literal("hu"),Type.Literal("ie"),Type.Literal("it"),Type.Literal("lt"),Type.Literal("lu"),Type.Literal("lv"),Type.Literal("nl"),Type.Literal("no"),Type.Literal("pl"),Type.Literal("ro"),Type.Literal("se"),Type.Literal("si"),Type.Literal("sk")], {"description":"market parameter."})}),async execute(params,config,context){return callCrawlora(config,context.signal,"zalando-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-zalando.");
 }
 return register(api);
};
export default plugin;
