// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-playstation",
 name: "Playstation by Crawlora",
 description: "Public Playstation data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_playstation_browse",description:"Use Crawlora to access public Playstation data.",parameters:Type.Object({"page": Type.Optional(Type.Integer({"description":"page parameter."})),"cc": Type.Optional(Type.String({"description":"cc parameter."})),"l": Type.Optional(Type.String({"description":"l parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"playstation-browse",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-playstation.");
 }
 return register(api);
};
export default plugin;
