// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-rover",
 name: "Rover by Crawlora",
 description: "Public Rover data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_rover_sitter_search",description:"Use Crawlora to access public Rover data.",parameters:Type.Object({"location": Type.String({"description":"location parameter."}),"service_type": Type.String({"description":"service_type parameter."}),"page": Type.Optional(Type.Integer({"description":"page parameter."})),"pet_type": Type.Optional(Type.String({"description":"pet_type parameter."})),"min_price": Type.Optional(Type.Integer({"description":"min_price parameter."})),"max_price": Type.Optional(Type.Integer({"description":"max_price parameter."})),"star_sitter_only": Type.Optional(Type.Boolean({"description":"star_sitter_only parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"rover-sitter-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-rover.");
 }
 return register(api);
};
export default plugin;
