// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-google",
 name: "Google by Crawlora",
 description: "Google search, news, videos, Maps, and Trends through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({
      name: "crawlora_google_search",
      description: "Search Google and return organic results.",
      parameters: Type.Object({
        q: Type.String({ description: "Search query." }),
        num: Type.Optional(Type.Integer({ minimum: 10, maximum: 100, description: "Number of results (10-100)." }))
      }),
      async execute(params, config, context) {
        return callCrawlora(config, context.signal, "google-search", {
          searchOption: {
            keyword: params.q,
            country: "us",
            language: "en",
            ...(params.num === undefined ? {} : { limit: params.num })
          }
        });
      }
    }),
tool({
      name: "crawlora_google_news",
      description: "Search Google News and return news results.",
      parameters: Type.Object({
        q: Type.String({ description: "Search query." }),
        count: Type.Optional(Type.Integer({ minimum: 1, maximum: 50, description: "Results per page (1-50)." }))
      }),
      async execute(params, config, context) {
        return callCrawlora(config, context.signal, "google-news", params);
      }
    }),
tool({
      name: "crawlora_google_videos",
      description: "Search Google Videos and return video results.",
      parameters: Type.Object({
        q: Type.String({ description: "Search query." }),
        count: Type.Optional(Type.Integer({ minimum: 1, maximum: 50, description: "Results per page (1-50)." }))
      }),
      async execute(params, config, context) {
        return callCrawlora(config, context.signal, "google-videos", params);
      }
    }),
tool({
      name: "crawlora_google_trends_explore",
      description: "Explore Google Trends interest for a query.",
      parameters: Type.Object({
        q: Type.String({ description: "Query or topic to explore." })
      }),
      async execute(params, config, context) {
        return callCrawlora(config, context.signal, "google-trends-explore", { request: { keywords: [params.q] } });
      }
    }),
tool({
      name: "crawlora_google_map_search",
      description: "Search Google Maps for places.",
      parameters: Type.Object({
        q: Type.String({ description: "Place or business search query." })
      }),
      async execute(params, config, context) {
        return callCrawlora(config, context.signal, "google-map-search", { mapSearchOption: { keyword: params.q } });
      }
    })],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-google.");
 }
 return register(api);
};
export default plugin;
