// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-deliveroo",
 name: "Deliveroo by Crawlora",
 description: "Public Deliveroo data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_deliveroo_search",description:"Use Crawlora to access public Deliveroo data.",parameters:Type.Object({"latitude": Type.Number({"description":"latitude parameter."}),"longitude": Type.Number({"description":"longitude parameter."}),"market": Type.Optional(Type.Union([Type.Literal("uk"),Type.Literal("ie"),Type.Literal("fr"),Type.Literal("it"),Type.Literal("be"),Type.Literal("ae"),Type.Literal("kw")], {"description":"market parameter."})),"limit": Type.Optional(Type.Integer({"description":"limit parameter."})),"collection": Type.Optional(Type.String({"description":"collection parameter."})),"cuisine": Type.Optional(Type.String({"description":"cuisine parameter."})),"dietary": Type.Optional(Type.String({"description":"dietary parameter."})),"dish": Type.Optional(Type.String({"description":"dish parameter."})),"top_rated": Type.Optional(Type.Boolean({"description":"top_rated parameter."})),"min_rating": Type.Optional(Type.Union([Type.Literal("3.5"),Type.Literal("4"),Type.Literal("4.5")], {"description":"min_rating parameter."})),"max_delivery_minutes": Type.Optional(Type.Union([Type.Literal("20"),Type.Literal("30"),Type.Literal("45")], {"description":"max_delivery_minutes parameter."})),"max_delivery_fee_pounds": Type.Optional(Type.Union([Type.Literal("1"),Type.Literal("2"),Type.Literal("3")], {"description":"max_delivery_fee_pounds parameter."})),"has_offer": Type.Optional(Type.Boolean({"description":"has_offer parameter."})),"sort": Type.Optional(Type.Union([Type.Literal("recommended"),Type.Literal("distance"),Type.Literal("time"),Type.Literal("rating")], {"description":"sort parameter."})),"deliveroos_choice": Type.Optional(Type.Boolean({"description":"deliveroos_choice parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"deliveroo-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-deliveroo.");
 }
 return register(api);
};
export default plugin;
