// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-pizzahut",
 name: "Pizzahut by Crawlora",
 description: "Public Pizzahut data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_pizzahut_menu",description:"Use Crawlora to access public Pizzahut data.",parameters:Type.Object({"store_number": Type.String({"description":"store_number parameter."}),"channel": Type.Optional(Type.Union([Type.Literal("WEB"),Type.Literal("MOBILE"),Type.Literal("POS"),Type.Literal("KIOSK"),Type.Literal("DOORDASH"),Type.Literal("UBEREATS"),Type.Literal("GRUBHUB"),Type.Literal("IOS"),Type.Literal("ANDROID"),Type.Literal("DELIVEROO"),Type.Literal("JUST_EAT"),Type.Literal("CALL_CENTER")], {"description":"channel parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"pizzahut-menu",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-pizzahut.");
 }
 return register(api);
};
export default plugin;
