// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-appstore",
 name: "Appstore by Crawlora",
 description: "Public Appstore data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_appstore_search",description:"Use Crawlora to access public Appstore data.",parameters:Type.Object({"term": Type.String({"description":"term parameter."}),"num": Type.Optional(Type.Integer({"description":"num parameter."})),"page": Type.Optional(Type.Integer({"description":"page parameter."})),"country": Type.Optional(Type.String({"description":"country parameter."})),"lang": Type.Optional(Type.String({"description":"lang parameter."})),"ids_only": Type.Optional(Type.Boolean({"description":"ids_only parameter."})),"platform": Type.Optional(Type.Union([Type.Literal("phone"),Type.Literal("pad"),Type.Literal("mac")], {"description":"platform parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"appstore-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-appstore.");
 }
 return register(api);
};
export default plugin;
