// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-sec",
 name: "SEC EDGAR by Crawlora",
 description: "SEC EDGAR company research, financial statements, filings, and insider transactions through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({
      name: "crawlora_sec_company_search",
      description: "Resolve a ticker or company name to SEC EDGAR companies (CIK, ticker, name).",
      parameters: Type.Object({
        q: Type.String({ description: "Ticker symbol or company name, e.g. apple or AAPL." })
      }),
      async execute(params, config, context) {
        return callCrawlora(config, context.signal, "sec-company-search", params);
      }
    }),
tool({
      name: "crawlora_sec_company_intelligence",
      description: "A company 360 from SEC data: profile, latest financial snapshot, latest 10-K/10-Q/8-K, and recent events.",
      parameters: Type.Object({
        ticker: Type.Optional(Type.String({ description: "Ticker symbol, e.g. AAPL." })),
        cik: Type.Optional(Type.String({ description: "SEC CIK (alternative to ticker)." }))
      }),
      async execute(params, config, context) {
        return callCrawlora(config, context.signal, "sec-company-intelligence", params);
      }
    }),
tool({
      name: "crawlora_sec_financials",
      description: "Normalized SEC financial statements (income, balance sheet, or cash flow) with computed margins and ratios.",
      parameters: Type.Object({
        ticker: Type.Optional(Type.String({ description: "Ticker symbol, e.g. AAPL." })),
        cik: Type.Optional(Type.String({ description: "SEC CIK (alternative to ticker)." })),
        statement: Type.Optional(Type.Union([
          Type.Literal("income"),
          Type.Literal("balance"),
          Type.Literal("cash_flow")
        ], { description: "Financial statement (default income)." })),
        period: Type.Optional(Type.Union([
          Type.Literal("annual"),
          Type.Literal("quarterly")
        ], { description: "Reporting period (default annual)." })),
        limit: Type.Optional(Type.Integer({ minimum: 1, maximum: 20, description: "Number of periods (1-20, default 5)." }))
      }),
      async execute(params, config, context) {
        return callCrawlora(config, context.signal, "sec-financials", params);
      }
    }),
tool({
      name: "crawlora_sec_filings",
      description: "List a company SEC EDGAR filings, filtered by form type and date.",
      parameters: Type.Object({
        ticker: Type.Optional(Type.String({ description: "Ticker symbol, e.g. AAPL." })),
        cik: Type.Optional(Type.String({ description: "SEC CIK (alternative to ticker)." })),
        form: Type.Optional(Type.String({ description: "Form type, e.g. 10-K, 10-Q, 8-K." })),
        limit: Type.Optional(Type.Integer({ minimum: 1, maximum: 500, description: "Max filings (1-500, default 50)." }))
      }),
      async execute(params, config, context) {
        return callCrawlora(config, context.signal, "sec-company-submissions", params);
      }
    }),
tool({
      name: "crawlora_sec_filing_sections",
      description: "Extract 10-K/10-Q/8-K item sections (Risk Factors, MD&A, etc.) from a filing as clean text.",
      parameters: Type.Object({
        accession: Type.String({ description: "Accession number, e.g. 0000320193-25-000079." }),
        ticker: Type.Optional(Type.String({ description: "Ticker symbol, e.g. AAPL." })),
        cik: Type.Optional(Type.String({ description: "SEC CIK (alternative to ticker)." })),
        items: Type.Optional(Type.String({ description: "Comma-separated item numbers, e.g. 1A,7." }))
      }),
      async execute(params, config, context) {
        return callCrawlora(config, context.signal, "sec-filing-sections", params);
      }
    }),
tool({
      name: "crawlora_sec_full_text_search",
      description: "Full-text search across SEC EDGAR filings, filtered by form and date.",
      parameters: Type.Object({
        q: Type.String({ description: "Search query (supports quoted phrases)." }),
        forms: Type.Optional(Type.String({ description: "Comma-separated form types, e.g. 10-K." }))
      }),
      async execute(params, config, context) {
        return callCrawlora(config, context.signal, "sec-full-text-search", params);
      }
    }),
tool({
      name: "crawlora_sec_insider",
      description: "Recent insider transactions (Forms 3/4/5) for a company.",
      parameters: Type.Object({
        ticker: Type.Optional(Type.String({ description: "Ticker symbol, e.g. AAPL." })),
        cik: Type.Optional(Type.String({ description: "SEC CIK (alternative to ticker)." })),
        limit: Type.Optional(Type.Integer({ minimum: 1, maximum: 30, description: "Max transactions (1-30, default 10)." }))
      }),
      async execute(params, config, context) {
        return callCrawlora(config, context.signal, "sec-insider", params);
      }
    })],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-sec.");
 }
 return register(api);
};
export default plugin;
