// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-boots",
 name: "Boots by Crawlora",
 description: "Public Boots data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_boots_search",description:"Use Crawlora to access public Boots data.",parameters:Type.Object({"q": Type.Optional(Type.String({"description":"q parameter."})),"category": Type.Optional(Type.String({"description":"category parameter."})),"filter": Type.Optional(Type.String({"description":"filter parameter."})),"price_min": Type.Optional(Type.Number({"description":"price_min parameter."})),"price_max": Type.Optional(Type.Number({"description":"price_max parameter."})),"in_stock": Type.Optional(Type.Boolean({"description":"in_stock parameter."})),"page": Type.Optional(Type.Integer({"description":"page parameter."})),"page_size": Type.Optional(Type.Integer({"description":"page_size parameter."})),"sort": Type.Optional(Type.Union([Type.Literal("relevance"),Type.Literal("price_low_to_high"),Type.Literal("price_high_to_low"),Type.Literal("top_rated"),Type.Literal("best_seller"),Type.Literal("newest")], {"description":"sort parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"boots-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-boots.");
 }
 return register(api);
};
export default plugin;
