// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-pandamart",
 name: "Pandamart by Crawlora",
 description: "Public Pandamart data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_pandamart_search",description:"Use Crawlora to access public Pandamart data.",parameters:Type.Object({"market": Type.Optional(Type.Union([Type.Literal("sg"),Type.Literal("pk"),Type.Literal("bd"),Type.Literal("hk"),Type.Literal("my"),Type.Literal("ph")], {"description":"market parameter."})),"latitude": Type.Number({"description":"latitude parameter."}),"longitude": Type.Number({"description":"longitude parameter."}),"limit": Type.Optional(Type.Integer({"description":"limit parameter."})),"offset": Type.Optional(Type.Integer({"description":"offset parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"pandamart-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-pandamart.");
 }
 return register(api);
};
export default plugin;
