// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-ubereats",
 name: "Ubereats by Crawlora",
 description: "Public Ubereats data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_ubereats_search",description:"Use Crawlora to access public Ubereats data.",parameters:Type.Object({"latitude": Type.Number({"description":"latitude parameter."}),"longitude": Type.Number({"description":"longitude parameter."}),"query": Type.Optional(Type.String({"description":"query parameter."})),"offset": Type.Optional(Type.Integer({"description":"offset parameter."})),"limit": Type.Optional(Type.Integer({"description":"limit parameter."})),"cursor": Type.Optional(Type.String({"description":"cursor parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"ubereats-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-ubereats.");
 }
 return register(api);
};
export default plugin;
