// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-imdb",
 name: "IMDb by Crawlora",
 description: "IMDb public title search through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_imdb_search",description:"Search public IMDb titles and names.",parameters:Type.Object({"query": Type.String({"description":"Title or name query."}),"limit": Type.Optional(Type.Number({"description":"Maximum results.","minimum":1,"maximum":100}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"imdb-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-imdb.");
 }
 return register(api);
};
export default plugin;
