// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-starbucks",
 name: "Starbucks by Crawlora",
 description: "Public Starbucks data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_starbucks_menu",description:"Use Crawlora to access public Starbucks data.",parameters:Type.Object({"store_number": Type.Optional(Type.String({"description":"store_number parameter."})),"market": Type.Optional(Type.Union([Type.Literal("us"),Type.Literal("ca")], {"description":"market parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"starbucks-menu",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-starbucks.");
 }
 return register(api);
};
export default plugin;
