// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-kfc",
 name: "Kfc by Crawlora",
 description: "Public Kfc data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_kfc_nearby",description:"Use Crawlora to access public Kfc data.",parameters:Type.Object({"latitude": Type.Number({"description":"latitude parameter."}),"longitude": Type.Number({"description":"longitude parameter."}),"radius_miles": Type.Optional(Type.Number({"description":"radius_miles parameter."})),"occasion": Type.Optional(Type.Union([Type.Literal("DELIVERY"),Type.Literal("CARRYOUT"),Type.Literal("DINE_IN"),Type.Literal("DRIVE_THRU"),Type.Literal("CATERING_CARRYOUT")], {"description":"occasion parameter."})),"max_results": Type.Optional(Type.Integer({"description":"max_results parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"kfc-nearby",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-kfc.");
 }
 return register(api);
};
export default plugin;
