// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-ebay",
 name: "eBay by Crawlora",
 description: "eBay marketplace listing search through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({
      name: "crawlora_ebay_search",
      description: "Search eBay listings.",
      parameters: Type.Object({
        q: Type.String({ description: "Search query." })
      }),
      async execute(params, config, context) {
        return callCrawlora(config, context.signal, "ebay-search", { option: { keyword: params.q } });
      }
    })],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-ebay.");
 }
 return register(api);
};
export default plugin;
