// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-brave",
 name: "Brave by Crawlora",
 description: "Public Brave data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_brave_search",description:"Use Crawlora to access public Brave data.",parameters:Type.Object({"q": Type.String({"description":"q parameter."}),"offset": Type.Optional(Type.Integer({"description":"offset parameter."})),"country": Type.Optional(Type.Union([Type.Literal("all"),Type.Literal("ar"),Type.Literal("at"),Type.Literal("au"),Type.Literal("be"),Type.Literal("br"),Type.Literal("ca"),Type.Literal("ch"),Type.Literal("cl"),Type.Literal("cn"),Type.Literal("de"),Type.Literal("dk"),Type.Literal("es"),Type.Literal("fi"),Type.Literal("fr"),Type.Literal("gb"),Type.Literal("gr"),Type.Literal("hk"),Type.Literal("id"),Type.Literal("in"),Type.Literal("it"),Type.Literal("jp"),Type.Literal("kr"),Type.Literal("mx"),Type.Literal("my"),Type.Literal("nl"),Type.Literal("no"),Type.Literal("nz"),Type.Literal("ph"),Type.Literal("pl"),Type.Literal("pt"),Type.Literal("ru"),Type.Literal("sa"),Type.Literal("se"),Type.Literal("sg"),Type.Literal("tr"),Type.Literal("tw"),Type.Literal("us"),Type.Literal("za")], {"description":"country parameter."})),"lang": Type.Optional(Type.Union([Type.Literal("de-de"),Type.Literal("en-ca"),Type.Literal("en-gb"),Type.Literal("en-in"),Type.Literal("en-us"),Type.Literal("fi-fi"),Type.Literal("fr-ca"),Type.Literal("fr-fr"),Type.Literal("ja-jp"),Type.Literal("pt-br"),Type.Literal("sq-al"),Type.Literal("sw-ke"),Type.Literal("zh-tw")], {"description":"lang parameter."})),"time_range": Type.Optional(Type.Union([Type.Literal("any"),Type.Literal("day"),Type.Literal("week"),Type.Literal("month"),Type.Literal("year"),Type.Literal("custom")], {"description":"time_range parameter."})),"date_from": Type.Optional(Type.String({"description":"date_from parameter."})),"date_to": Type.Optional(Type.String({"description":"date_to parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"brave-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-brave.");
 }
 return register(api);
};
export default plugin;
