// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-amazon",
 name: "Amazon by Crawlora",
 description: "Amazon product search and product details through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({
      name: "crawlora_amazon_search",
      description: "Search Amazon for products.",
      parameters: Type.Object({
        k: Type.String({ description: "Search keywords." })
      }),
      async execute(params, config, context) {
        return callCrawlora(config, context.signal, "amazon-search", params);
      }
    }),
tool({
      name: "crawlora_amazon_product",
      description: "Fetch a single Amazon product by ASIN.",
      parameters: Type.Object({
        asin: Type.String({ description: "Amazon ASIN." })
      }),
      async execute(params, config, context) {
        return callCrawlora(config, context.signal, "amazon-product", params);
      }
    })],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-amazon.");
 }
 return register(api);
};
export default plugin;
