// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-reddit",
 name: "Reddit by Crawlora",
 description: "Reddit public post search through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_reddit_search",description:"Search public Reddit posts.",parameters:Type.Object({"q": Type.String({"description":"Search query."}),"subreddit": Type.Optional(Type.String({"description":"Limit results to a subreddit."})),"sort": Type.Optional(Type.Union([Type.Literal("relevance"),Type.Literal("hot"),Type.Literal("new"),Type.Literal("top"),Type.Literal("comments")], {"description":"Sort order."})),"time": Type.Optional(Type.Union([Type.Literal("hour"),Type.Literal("day"),Type.Literal("week"),Type.Literal("month"),Type.Literal("year"),Type.Literal("all")], {"description":"Time window."})),"limit": Type.Optional(Type.Integer({"description":"Maximum posts.","minimum":1,"maximum":100}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"reddit-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-reddit.");
 }
 return register(api);
};
export default plugin;
