// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-spotify",
 name: "Spotify by Crawlora",
 description: "Spotify catalog search through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_spotify_search",description:"Search Spotify for tracks, artists, albums, playlists, and podcasts.",parameters:Type.Object({"q": Type.String({"description":"Search query."}),"limit": Type.Optional(Type.Integer({"description":"Maximum results per page.","minimum":1,"maximum":50})),"offset": Type.Optional(Type.Integer({"description":"Result offset.","minimum":0}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"spotify-search",params);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-spotify.");
 }
 return register(api);
};
export default plugin;
