// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-chromewebstore",
 name: "Chromewebstore by Crawlora",
 description: "Public Chromewebstore data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_chromewebstore_search",description:"Use Crawlora to access public Chromewebstore data.",parameters:Type.Object({"term": Type.String({"description":"term parameter."}),"num": Type.Optional(Type.Integer({"description":"num parameter."})),"country": Type.Optional(Type.String({"description":"country parameter."})),"lang": Type.Optional(Type.String({"description":"lang parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"chromewebstore-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-chromewebstore.");
 }
 return register(api);
};
export default plugin;
