// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-agoda",
 name: "Agoda by Crawlora",
 description: "Public Agoda data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_agoda_activities_search",description:"Use Crawlora to access public Agoda data.",parameters:Type.Object({"keyword": Type.Optional(Type.String({"description":"keyword parameter."})),"city_id": Type.Optional(Type.Integer({"description":"city_id parameter."})),"city": Type.Optional(Type.String({"description":"city parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"agoda-activities-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-agoda.");
 }
 return register(api);
};
export default plugin;
