// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-tokopedia",
 name: "Tokopedia by Crawlora",
 description: "Public Tokopedia data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_tokopedia_search",description:"Use Crawlora to access public Tokopedia data.",parameters:Type.Object({"q": Type.String({"description":"q parameter."}),"page": Type.Optional(Type.Integer({"description":"page parameter."})),"sort": Type.Optional(Type.Union([Type.Literal("3"),Type.Literal("4"),Type.Literal("5"),Type.Literal("9"),Type.Literal("23")], {"description":"sort parameter."})),"filter": Type.Optional(Type.String({"description":"filter parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"tokopedia-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-tokopedia.");
 }
 return register(api);
};
export default plugin;
