// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-doordash",
 name: "Doordash by Crawlora",
 description: "Public Doordash data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_doordash_search",description:"Use Crawlora to access public Doordash data.",parameters:Type.Object({"query": Type.String({"description":"query parameter."}),"latitude": Type.Number({"description":"latitude parameter."}),"longitude": Type.Number({"description":"longitude parameter."}),"tag": Type.Optional(Type.String({"description":"tag parameter."})),"dashPassOnly": Type.Optional(Type.Boolean({"description":"dashPassOnly parameter."})),"asapOnly": Type.Optional(Type.Boolean({"description":"asapOnly parameter."})),"pickupOnly": Type.Optional(Type.Boolean({"description":"pickupOnly parameter."})),"maxDistanceMiles": Type.Optional(Type.Number({"description":"maxDistanceMiles parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"doordash-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-doordash.");
 }
 return register(api);
};
export default plugin;
