// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-chick-fil-a",
 name: "Chick Fil A by Crawlora",
 description: "Public Chick Fil A data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_chick_fil_a_content",description:"Use Crawlora to access public Chick Fil A data.",parameters:Type.Object({"type": Type.Union([Type.Literal("press-room"),Type.Literal("story"),Type.Literal("page"),Type.Literal("legal"),Type.Literal("downloadable-asset")], {"description":"type parameter."}),"search": Type.Optional(Type.String({"description":"search parameter."})),"page": Type.Optional(Type.Integer({"description":"page parameter."})),"per_page": Type.Optional(Type.Integer({"description":"per_page parameter."})),"include_body": Type.Optional(Type.Boolean({"description":"include_body parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"chick-fil-a-content",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-chick-fil-a.");
 }
 return register(api);
};
export default plugin;
