// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-culvers",
 name: "Culvers by Crawlora",
 description: "Public Culvers data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_culvers_directory",description:"Use Crawlora to access public Culvers data.",parameters:Type.Object({"page": Type.Optional(Type.Integer({"description":"page parameter."})),"page_size": Type.Optional(Type.Integer({"description":"page_size parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"culvers-directory",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-culvers.");
 }
 return register(api);
};
export default plugin;
