// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-rottentomatoes",
 name: "Rottentomatoes by Crawlora",
 description: "Public Rottentomatoes data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_rottentomatoes_browse_movies",description:"Use Crawlora to access public Rottentomatoes data.",parameters:Type.Object({"list": Type.Optional(Type.Union([Type.Literal("movies_in_theaters"),Type.Literal("movies_at_home"),Type.Literal("movies_coming_soon")], {"description":"list parameter."})),"sort": Type.Optional(Type.Union([Type.Literal("popular"),Type.Literal("newest"),Type.Literal("top_box_office")], {"description":"sort parameter."})),"limit": Type.Optional(Type.Integer({"description":"limit parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"rottentomatoes-browse-movies",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-rottentomatoes.");
 }
 return register(api);
};
export default plugin;
