// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-vinted",
 name: "Vinted by Crawlora",
 description: "Public Vinted data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_vinted_catalog",description:"Use Crawlora to access public Vinted data.",parameters:Type.Object({"search_text": Type.String({"description":"search_text parameter."}),"price_from": Type.Optional(Type.Number({"description":"price_from parameter."})),"price_to": Type.Optional(Type.Number({"description":"price_to parameter."})),"order": Type.Optional(Type.Union([Type.Literal("relevance"),Type.Literal("newest_first"),Type.Literal("price_high_to_low"),Type.Literal("price_low_to_high")], {"description":"order parameter."})),"page": Type.Optional(Type.Integer({"description":"page parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"vinted-catalog",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-vinted.");
 }
 return register(api);
};
export default plugin;
