// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-7now",
 name: "7now by Crawlora",
 description: "Public 7now data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_7now_catalog",description:"Use Crawlora to access public 7now data.",parameters:Type.Object({"store_id": Type.String({"description":"store_id parameter."}),"lat": Type.Optional(Type.Number({"description":"lat parameter."})),"lon": Type.Optional(Type.Number({"description":"lon parameter."})),"skip": Type.Optional(Type.Integer({"description":"skip parameter."})),"limit": Type.Optional(Type.Integer({"description":"limit parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"7now-catalog",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-7now.");
 }
 return register(api);
};
export default plugin;
