// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-shopify",
 name: "Shopify by Crawlora",
 description: "Public Shopify data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_shopify_collection_products",description:"Use Crawlora to access public Shopify data.",parameters:Type.Object({"handle": Type.String({"description":"handle path parameter."}),"url": Type.String({"description":"url parameter."}),"page": Type.Optional(Type.Integer({"description":"page parameter."})),"limit": Type.Optional(Type.Integer({"description":"limit parameter."})),"sortBy": Type.Optional(Type.Union([Type.Literal("sortLTH"),Type.Literal("sortHTL"),Type.Literal("newest")], {"description":"sortBy parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"shopify-collection-products",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-shopify.");
 }
 return register(api);
};
export default plugin;
