// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-carsdotcom",
 name: "Carsdotcom by Crawlora",
 description: "Public Carsdotcom data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_carsdotcom_search",description:"Use Crawlora to access public Carsdotcom data.",parameters:Type.Object({"zip": Type.Optional(Type.String({"description":"zip parameter."})),"radius": Type.Optional(Type.Integer({"description":"radius parameter."})),"stock_type": Type.Optional(Type.Union([Type.Literal("new"),Type.Literal("used"),Type.Literal("cpo"),Type.Literal("all")], {"description":"stock_type parameter."})),"page": Type.Optional(Type.Integer({"description":"page parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"carsdotcom-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-carsdotcom.");
 }
 return register(api);
};
export default plugin;
