// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-yahoo-finance",
 name: "Yahoo Finance by Crawlora",
 description: "Yahoo Finance ticker quotes through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({
      name: "crawlora_yahoo_finance_ticker_quote",
      description: "Get a Yahoo Finance quote for a ticker.",
      parameters: Type.Object({
        ticker: Type.String({ description: "Ticker symbol, e.g. NVDA." })
      }),
      async execute(params, config, context) {
        return callCrawlora(config, context.signal, "yahoo-finance-ticker-quote", { symbol: params.ticker });
      }
    })],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-yahoo-finance.");
 }
 return register(api);
};
export default plugin;
