// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-jobs",
 name: "Jobs by Crawlora",
 description: "ATS discovery and hiring signals across public company job boards through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({
      name: "crawlora_jobs_hiring_signals",
      description: "Aggregate a company's ATS job board into hiring signals: total open roles, department/location breakdowns, remote share, and how many roles are new in the last 7/30 days.",
      parameters: Type.Object({
        provider: Type.Union([
          Type.Literal("greenhouse"),
          Type.Literal("lever"),
          Type.Literal("ashby"),
          Type.Literal("workday"),
          Type.Literal("smartrecruiters")
        ], { description: "ATS provider." }),
        token: Type.Optional(Type.String({ description: "Greenhouse board token." })),
        company: Type.Optional(Type.String({ description: "Lever or SmartRecruiters company slug." })),
        org: Type.Optional(Type.String({ description: "Ashby org slug." })),
        tenant: Type.Optional(Type.String({ description: "Workday tenant." })),
        datacenter: Type.Optional(Type.String({ description: "Workday datacenter shard (wd1, wd3, wd5...)." })),
        site: Type.Optional(Type.String({ description: "Workday career site." }))
      }),
      async execute(params, config, context) {
        return callCrawlora(config, context.signal, "jobs-hiring-signals", params);
      }
    }),
tool({
      name: "crawlora_jobs_company_search",
      description: "Find which ATS (Greenhouse, Lever, Ashby, SmartRecruiters) a company uses from its careers slug, with open-role counts.",
      parameters: Type.Object({
        slug: Type.String({ description: "Company careers slug, e.g. stripe." })
      }),
      async execute(params, config, context) {
        return callCrawlora(config, context.signal, "jobs-company-search", params);
      }
    })],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-jobs.");
 }
 return register(api);
};
export default plugin;
