// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-apple-books",
 name: "Apple Books by Crawlora",
 description: "Apple Books public catalog search through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_apple_books_search",description:"Search the public Apple Books catalog.",parameters:Type.Object({"term": Type.String({"description":"Book search term."}),"country": Type.Optional(Type.String({"description":"Store country code."})),"lang": Type.Optional(Type.String({"description":"Language code."})),"limit": Type.Optional(Type.Number({"description":"Maximum results.","minimum":1,"maximum":200})),"page": Type.Optional(Type.Number({"description":"Page number.","minimum":1}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"apple-books-search",params);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-apple-books.");
 }
 return register(api);
};
export default plugin;
