// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-pitchbook",
 name: "Pitchbook by Crawlora",
 description: "Public Pitchbook data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_pitchbook_company",description:"Use Crawlora to access public Pitchbook data.",parameters:Type.Object({"id": Type.Optional(Type.String({"description":"id parameter."})),"url": Type.Optional(Type.String({"description":"url parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"pitchbook-company",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-pitchbook.");
 }
 return register(api);
};
export default plugin;
