// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-foodpanda",
 name: "Foodpanda by Crawlora",
 description: "Public Foodpanda data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_foodpanda_restaurant",description:"Use Crawlora to access public Foodpanda data.",parameters:Type.Object({"market": Type.Optional(Type.Union([Type.Literal("sg"),Type.Literal("pk"),Type.Literal("bd"),Type.Literal("hk"),Type.Literal("my"),Type.Literal("ph"),Type.Literal("la"),Type.Literal("kh"),Type.Literal("tw"),Type.Literal("mm")], {"description":"market parameter."})),"code": Type.String({"description":"code parameter."}),"latitude": Type.Optional(Type.Number({"description":"latitude parameter."})),"longitude": Type.Optional(Type.Number({"description":"longitude parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"foodpanda-restaurant",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-foodpanda.");
 }
 return register(api);
};
export default plugin;
