// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-ikea",
 name: "Ikea by Crawlora",
 description: "Public Ikea data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_ikea_product",description:"Use Crawlora to access public Ikea data.",parameters:Type.Object({"item_no": Type.String({"description":"item_no parameter."}),"country": Type.Optional(Type.String({"description":"country parameter."})),"language": Type.Optional(Type.String({"description":"language parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"ikea-product",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-ikea.");
 }
 return register(api);
};
export default plugin;
