// Reviewed platform package definitions; tools stay in src/index.ts.
// The SDK catalog also drives the long tail below so every public family can
// have a focused package without hand-copying parameter contracts.
import { operations as sdkOperations } from '../node_modules/@crawlora-org/sdk/src/operations.js';

const autoCatalog = [
 ['adidas','adidas-product'],['agoda','agoda-activities-search'],['allbirds','allbirds-collection-products'],['anime','anime-character-search'],['autotrader','autotrader-search'],['bbb','bbb-business'],['bbc','bbc-article'],['bestbuy','bestbuy-product'],['bilibili','bilibili-anime-home'],['brave','brave-search'],['burgerking','burgerking-product'],['capterra','capterra-product'],['carmax','carmax-search'],['carsdotcom','carsdotcom-search'],['chewy','chewy-product'],['cnn','cnn-article'],['costco','costco-product'],['cricinfo','cricinfo-calendar'],['depop','depop-search'],['discogs','discogs-search'],['dominos','dominos-menu'],['doordash','doordash-search'],['espn','espn-news'],['etsy','etsy-search'],['expedia','expedia-activities-search'],['facebook','facebook-marketplace-search'],['fiverr','fiverr-search'],['foodpanda','foodpanda-restaurant'],['gdelt','gdelt-search'],['geocoding','geocoding-search'],['goodreads','goodreads-search'],['googleplay','googleplay-app'],['grubhub','grubhub-restaurant'],['guardian','guardian-article'],['hm','hm-listing'],['homedepot','homedepot-categories'],['hotels','hotels-property'],['ikea','ikea-product'],['indeed','indeed-job'],['instacart','instacart-search'],['instagram','instagram-post'],['kickstarter','kickstarter-project'],['linkedin','linkedin-company'],['macys','macys-product'],['manga','manga-search'],['mercari','mercari-item'],['metacritic','metacritic-game'],['mlb','mlb-game'],['nike','nike-product'],['numbeo','numbeo-cost-of-living-city'],['opentable','opentable-restaurant'],['patreon','patreon-creator'],['playstation','playstation-browse'],['producthunt','producthunt-product'],['redfin','redfin-property'],['rightmove','rightmove-property'],['roblox','roblox-game'],['rottentomatoes','rottentomatoes-browse-movies'],['rover','rover-sitter-search'],['sephora','sephora-product'],['shein','shein-category-goods'],['shopify','shopify-collection-products'],['soundcloud','soundcloud-search'],['starbucks','starbucks-menu'],['stockx','stockx-product'],['strava','strava-route-detail'],['subway','subway-nearby'],['tmdb','tmdb-movie'],['tripadvisor','tripadvisor-search'],['trustpilot','trustpilot-business'],['twitch','twitch-search'],['upwork','upwork-search'],['vinted','vinted-catalog'],['walmart','walmart-search'],['wayfair','wayfair-product'],['whatnot','whatnot-browse'],['wolt','wolt-restaurant'],['x','x-post'],['zara','zara-category-products'],['zomato','zomato-restaurant'],['leboncoin','leboncoin-search'],['letterboxd','letterboxd-search'],['mcdonalds','mcdonalds-item']
];
const autoCatalogMore = [
 ['amazon-jobs','amazon-jobs-search'],['appstore','appstore-search'],['arbys','arbys-menu'],['audible','audible-search'],['boxofficemojo','boxofficemojo-brand'],['bluesky','bluesky-profile'],['bonhams','bonhams-auction-search'],['boots','boots-search'],['chick-fil-a','chick-fil-a-content'],['chipotle','chipotle-menu'],['chromewebstore','chromewebstore-search'],['courtlistener','courtlistener-search'],['culvers','culvers-directory'],['cvs','cvs-search'],['datasets','datasets-airbnb-markets-search'],['deliveroo','deliveroo-search'],['draftkings','draftkings-event'],['duckduckgo','duckduckgo-search'],['dunkin','dunkin-nearby'],['everlane','everlane-product'],['fashionnova','fashionnova-product'],['fiveguys','fiveguys-nearby'],['goat','goat-product'],['googlepatents','googlepatents-search'],['gymshark','gymshark-product'],['importyeti','importyeti-search'],['jimmy-johns','jimmy-johns-nearby'],['justeat','justeat-search'],['justwatch','justwatch-discover'],['kfc','kfc-nearby'],['kohls','kohls-stores'],['kroger','kroger-search'],['lazada','lazada-search'],['lululemon','lululemon-product'],['meta-jobs','meta-jobs-search'],['metaculus','metaculus-question'],['papajohns','papajohns-directory'],['panera','panera-cafe'],['pizzahut','pizzahut-menu'],['poshmark','poshmark-search'],['raisingcanes','raisingcanes-nearby'],['rothys','rothys-product'],['samsclub','samsclub-product'],['shakeshack','shakeshack-nearby'],['sonic','sonic-nearby'],['sparkfun','sparkfun-search'],['taco-bell','taco-bell-menu'],['tes-job','tes-job-search'],['tesla-jobs','tesla-jobs-list'],['thebodyshop','thebodyshop-product'],['threads','threads-search'],['ticketmaster','ticketmaster-attraction'],['ticketweb','ticketweb-search'],['tokopedia','tokopedia-search'],['tripcom','tripcom-hotels-search'],['trustmrr','trustmrr-marketplace'],['ubereats','ubereats-search'],['ulta','ulta-product'],['usptoppubs','usptoppubs-search'],['walgreens','walgreens-stores'],['wendys','wendys-nearby'],['whataburger','whataburger-store'],['wingstop','wingstop-nearby'],['wish','wish-search'],['zalando','zalando-search'],['zappos','zappos-search'],['zaxbys','zaxbys-nearby'],['yahoo','yahoo-autos-home']
];
const titleFor = slug => slug.split('-').map(word=>word[0].toUpperCase()+word.slice(1)).join(' ');
const autoPlatforms = [...autoCatalog, ...autoCatalogMore].map(([slug, operation]) => {
 const meta=sdkOperations[operation];
 if (!meta) throw new Error(`Unknown SDK operation ${operation}`);
 const params=[...(meta.pathParams??[]).map(name=>({name,type:'string',required:true,description:`${name} path parameter.`})),...(meta.queryParams??[]).map(param=>({name:param.name,type:param.type??'string',required:Boolean(param.required),enum:param.enum,description:`${param.name} parameter.`}))];
 const toolName=`crawlora_${slug.replaceAll('-','_')}_${operation.replaceAll('-','_').replace(`${slug.replaceAll('-','_')}_`,'')}`;
 return {slug,title:titleFor(slug),schemaMetadata:true,tools:[toolName],customTools:[{name:toolName,operation,description:`Use Crawlora to access public ${titleFor(slug)} data.`,params}],example:`Retrieve public ${titleFor(slug)} data.`,summary:`Public ${titleFor(slug)} data through Crawlora.`};
});
export const platforms = [
 {slug:'amazon',version:'1.0.1',schemaMetadata:true,title:'Amazon',tools:['crawlora_amazon_search','crawlora_amazon_product'],example:'Search Amazon for noise cancelling headphones and inspect a matching product.',summary:'Amazon product search and product details through Crawlora.'},
 {slug:'youtube',title:'YouTube',tools:['crawlora_youtube_transcript'],example:'Get the transcript of YouTube video dQw4w9WgXcQ.',summary:'YouTube video transcripts through Crawlora.'},
 {slug:'google',title:'Google',tools:['crawlora_google_search','crawlora_google_news','crawlora_google_videos','crawlora_google_trends_explore','crawlora_google_map_search'],example:'Find coffee shops in San Francisco and search for recent coffee industry news.',summary:'Google search, news, videos, Maps, and Trends through Crawlora.'},
 {slug:'sec',version:'1.0.1',schemaMetadata:true,title:'SEC EDGAR',tools:['crawlora_sec_company_search','crawlora_sec_company_intelligence','crawlora_sec_financials','crawlora_sec_filings','crawlora_sec_filing_sections','crawlora_sec_full_text_search','crawlora_sec_insider'],example:'Resolve AAPL, then get annual financials and recent SEC filings.',summary:'SEC EDGAR company research, financial statements, filings, and insider transactions through Crawlora.'},
 {"slug": "bing", "title": "Bing", "schemaMetadata": true, "tools": ["crawlora_bing_search"], "example": "Search Bing for recent battery recycling research.", "summary": "Bing web search through Crawlora."},
 {"slug": "ebay", "title": "eBay", "schemaMetadata": true, "tools": ["crawlora_ebay_search"], "example": "Find vintage mechanical keyboards on eBay.", "summary": "eBay marketplace listing search through Crawlora."},
 {"slug": "yahoo-finance", "title": "Yahoo Finance", "schemaMetadata": true, "tools": ["crawlora_yahoo_finance_ticker_quote"], "example": "Get the latest available AAPL stock quote.", "summary": "Yahoo Finance ticker quotes through Crawlora."},
 {"slug": "greenhouse", "title": "Greenhouse", "schemaMetadata": true, "tools": ["crawlora_jobs_greenhouse_board"], "example": "List current public jobs on Stripe’s Greenhouse board.", "summary": "Public Greenhouse job-board listings through Crawlora."},
 {"slug": "lever", "title": "Lever", "schemaMetadata": true, "tools": ["crawlora_jobs_lever_postings"], "example": "List current public jobs on Spotify’s Lever board.", "summary": "Public Lever job postings through Crawlora."},
 {"slug": "ashby", "title": "Ashby", "schemaMetadata": true, "tools": ["crawlora_jobs_ashby_board"], "example": "List current public jobs on OpenAI’s Ashby board.", "summary": "Public Ashby job-board listings through Crawlora."},
 {"slug": "jobs", "title": "Jobs", "schemaMetadata": true, "tools": ["crawlora_jobs_hiring_signals", "crawlora_jobs_company_search"], "example": "Find a company’s ATS and summarize its current hiring signals.", "summary": "ATS discovery and hiring signals across public company job boards through Crawlora."},
 {slug:'spotify',title:'Spotify',schemaMetadata:true,tools:['crawlora_spotify_search'],customTools:[{name:'crawlora_spotify_search',operation:'spotify-search',description:'Search Spotify for tracks, artists, albums, playlists, and podcasts.',params:[{name:'q',type:'string',required:true,description:'Search query.'},{name:'limit',type:'integer',minimum:1,maximum:50,description:'Maximum results per page.'},{name:'offset',type:'integer',minimum:0,description:'Result offset.'}]}],example:'Search Spotify for ambient focus music.',summary:'Spotify catalog search through Crawlora.'},
 {slug:'tiktok',title:'TikTok',schemaMetadata:true,tools:['crawlora_tiktok_post'],customTools:[{name:'crawlora_tiktok_post',operation:'tiktok-post',description:'Fetch a public TikTok post by ID.',params:[{name:'id',type:'string',required:true,description:'TikTok post ID.'}]}],example:'Fetch a public TikTok post by ID.',summary:'TikTok public post data through Crawlora.'},
 {slug:'reddit',title:'Reddit',schemaMetadata:true,tools:['crawlora_reddit_search'],customTools:[{name:'crawlora_reddit_search',operation:'reddit-search',description:'Search public Reddit posts.',params:[{name:'q',type:'string',required:true,description:'Search query.'},{name:'subreddit',type:'string',description:'Limit results to a subreddit.'},{name:'sort',type:'string',enum:['relevance','hot','new','top','comments'],description:'Sort order.'},{name:'time',type:'string',enum:['hour','day','week','month','year','all'],description:'Time window.'},{name:'limit',type:'integer',minimum:1,maximum:100,description:'Maximum posts.'}]}],example:'Search Reddit for discussions about web scraping.',summary:'Reddit public post search through Crawlora.'},
 {slug:'github',version:'1.0.1',title:'GitHub',schemaMetadata:true,tools:['crawlora_github_search_repositories'],customTools:[{name:'crawlora_github_search_repositories',operation:'github-search-repositories',description:'Search public GitHub repositories.',params:[{name:'q',type:'string',required:true,description:'Repository search query.'},{name:'sort',type:'string',enum:['stars','forks','help-wanted-issues','updated'],description:'Sort order.'},{name:'order',type:'string',enum:['asc','desc'],description:'Sort direction.'},{name:'page',type:'integer',minimum:1,description:'Page number.'},{name:'per_page',type:'integer',minimum:1,maximum:100,description:'Results per page.'}]}],example:'Find popular open-source browser automation repositories.',summary:'GitHub repository search through Crawlora.'},
 {slug:'pinterest',title:'Pinterest',schemaMetadata:true,tools:['crawlora_pinterest_search'],customTools:[{name:'crawlora_pinterest_search',operation:'pinterest-search',description:'Search public Pinterest pins and boards.',params:[{name:'query',type:'string',required:true,description:'Search query.'}]}],example:'Search Pinterest for minimalist kitchen ideas.',summary:'Pinterest public search through Crawlora.'},
 {slug:'airbnb',title:'Airbnb',schemaMetadata:true,tools:['crawlora_airbnb_search'],customTools:[{name:'crawlora_airbnb_search',operation:'airbnb-search',description:'Search public Airbnb listings by location.',params:[{name:'location',type:'string',required:true,description:'City, region, or neighborhood.'},{name:'check_in',type:'string',description:'Check-in date (YYYY-MM-DD).'},{name:'check_out',type:'string',description:'Check-out date (YYYY-MM-DD).'},{name:'adults',type:'number',minimum:1,description:'Number of adults.'},{name:'page',type:'number',minimum:1,description:'Page number.'},{name:'currency',type:'string',description:'Currency code.'}]}],example:'Find Airbnb stays in Lisbon for a weekend.',summary:'Airbnb public listing search through Crawlora.'},
 {slug:'booking',title:'Booking.com',schemaMetadata:true,tools:['crawlora_booking_search'],customTools:[{name:'crawlora_booking_search',operation:'booking-search',description:'Search public Booking.com accommodations.',params:[{name:'query',type:'string',required:true,description:'Destination or property query.'},{name:'checkin',type:'string',required:true,description:'Check-in date (YYYY-MM-DD).'},{name:'checkout',type:'string',required:true,description:'Check-out date (YYYY-MM-DD).'},{name:'adults',type:'number',minimum:1,description:'Number of adults.'},{name:'rooms',type:'number',minimum:1,description:'Number of rooms.'},{name:'children',type:'number',minimum:0,description:'Number of children.'},{name:'page',type:'number',minimum:1,description:'Page number.'}]}],example:'Search Booking.com hotels in Tokyo for next month.',summary:'Booking.com public accommodation search through Crawlora.'},
 {slug:'yelp',title:'Yelp',schemaMetadata:true,tools:['crawlora_yelp_search'],customTools:[{name:'crawlora_yelp_search',operation:'yelp-search',description:'Search public Yelp businesses.',params:[{name:'term',type:'string',required:true,description:'Business or service query.'},{name:'location',type:'string',required:true,description:'City, address, or region.'},{name:'limit',type:'number',minimum:1,maximum:50,description:'Maximum businesses.'},{name:'offset',type:'number',minimum:0,description:'Result offset.'}]}],example:'Find highly rated ramen restaurants in San Francisco.',summary:'Yelp public business search through Crawlora.'},
 {slug:'zillow',title:'Zillow',schemaMetadata:true,tools:['crawlora_zillow_search'],customTools:[{name:'crawlora_zillow_search',operation:'zillow-search',description:'Search public Zillow property listings.',params:[{name:'location',type:'string',required:true,description:'City, ZIP code, or neighborhood.'},{name:'page',type:'number',minimum:1,description:'Page number.'},{name:'status',type:'string',enum:['for_sale','sale','for-sale','for_rent','rent','for-rent','sold'],description:'Listing status.'}]}],example:'Browse homes for sale in Austin.',summary:'Zillow public property search through Crawlora.'},
 {slug:'imdb',title:'IMDb',schemaMetadata:true,tools:['crawlora_imdb_search'],customTools:[{name:'crawlora_imdb_search',operation:'imdb-search',description:'Search public IMDb titles and names.',params:[{name:'query',type:'string',required:true,description:'Title or name query.'},{name:'limit',type:'number',minimum:1,maximum:100,description:'Maximum results.'}]}],example:'Search IMDb for science-fiction films.',summary:'IMDb public title search through Crawlora.'},
 {slug:'steam',title:'Steam',schemaMetadata:true,tools:['crawlora_steam_app'],customTools:[{name:'crawlora_steam_app',operation:'steam-app',description:'Fetch public Steam app details.',params:[{name:'appid',type:'string',required:true,description:'Steam application ID.'},{name:'cc',type:'string',description:'Country code.'},{name:'l',type:'string',description:'Language code.'},{name:'filters',type:'string',description:'Optional response filters.'}]}],example:'Inspect the public Steam metadata for an app.',summary:'Steam public app data through Crawlora.'},
 {slug:'coingecko',title:'CoinGecko',schemaMetadata:true,tools:['crawlora_coingecko_markets'],customTools:[{name:'crawlora_coingecko_markets',operation:'coingecko-markets',description:'Fetch public cryptocurrency market rankings.',params:[{name:'vs_currency',type:'string',required:true,description:'Quote currency, such as usd or eur.'},{name:'page',type:'number',minimum:1,description:'Page number.'},{name:'limit',type:'number',minimum:1,maximum:250,description:'Markets per page.'}]}],example:'Get the top cryptocurrency markets priced in USD.',summary:'CoinGecko public market data through Crawlora.'},
 {slug:'polymarket',title:'Polymarket',schemaMetadata:true,tools:['crawlora_polymarket_events'],customTools:[{name:'crawlora_polymarket_events',operation:'polymarket-events',description:'List public Polymarket prediction events.',params:[{name:'limit',type:'number',minimum:1,maximum:100,description:'Maximum events.'},{name:'offset',type:'number',minimum:0,description:'Result offset.'},{name:'order',type:'string',enum:['volume24hr','volume','liquidity','endDate','updatedAt','createdAt','id','slug','title','question','label'],description:'Sort field.'},{name:'ascending',type:'boolean',description:'Sort ascending.'},{name:'closed',type:'string',enum:['true','false'],description:'Filter closed events.'}]}],example:'List active prediction markets on Polymarket.',summary:'Polymarket public event data through Crawlora.'},
 {slug:'kalshi',title:'Kalshi',schemaMetadata:true,tools:['crawlora_kalshi_events'],customTools:[{name:'crawlora_kalshi_events',operation:'kalshi-events',description:'List public Kalshi prediction events.',params:[{name:'limit',type:'number',minimum:1,maximum:1000,description:'Maximum events.'},{name:'cursor',type:'string',description:'Pagination cursor.'},{name:'series_ticker',type:'string',description:'Filter by series ticker.'},{name:'category',type:'string',description:'Filter by category.'},{name:'status',type:'string',enum:['open','closed','settled'],description:'Event status.'},{name:'with_nested_markets',type:'boolean',description:'Include nested markets.'}]}],example:'List open Kalshi events with their nested markets.',summary:'Kalshi public event data through Crawlora.'},
 {slug:'apple-books',title:'Apple Books',schemaMetadata:true,tools:['crawlora_apple_books_search'],customTools:[{name:'crawlora_apple_books_search',operation:'apple-books-search',description:'Search the public Apple Books catalog.',params:[{name:'term',type:'string',required:true,description:'Book search term.'},{name:'country',type:'string',description:'Store country code.'},{name:'lang',type:'string',description:'Language code.'},{name:'limit',type:'number',minimum:1,maximum:200,description:'Maximum results.'},{name:'page',type:'number',minimum:1,description:'Page number.'}]}],example:'Search Apple Books for books about machine learning.',summary:'Apple Books public catalog search through Crawlora.'},
 {slug:'apple-jobs',title:'Apple Jobs',schemaMetadata:true,tools:['crawlora_apple_jobs_search'],customTools:[{name:'crawlora_apple_jobs_search',operation:'apple-jobs-search',description:'Search public Apple job openings.',params:[{name:'q',type:'string',required:true,description:'Role or keyword query.'},{name:'location',type:'string',description:'Location filter.'},{name:'page',type:'number',minimum:1,description:'Page number.'}]}],example:'Search Apple Jobs for machine-learning roles.',summary:'Apple public job search through Crawlora.'},
 {slug:'opensea',title:'OpenSea',schemaMetadata:true,tools:['crawlora_opensea_collection'],customTools:[{name:'crawlora_opensea_collection',operation:'opensea-collection',description:'Fetch public OpenSea collection data.',params:[{name:'slug',type:'string',required:true,description:'OpenSea collection slug.'}]}],example:'Inspect a public OpenSea NFT collection.',summary:'OpenSea public NFT collection data through Crawlora.'},
 ...autoPlatforms,
];
