// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-swiggy",
 name: "Swiggy by Crawlora",
 description: "Public Swiggy data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_swiggy_search",description:"Use Crawlora to access public Swiggy data.",parameters:Type.Object({"latitude": Type.Number({"description":"latitude parameter."}),"longitude": Type.Number({"description":"longitude parameter."}),"query": Type.Optional(Type.String({"description":"query parameter."})),"collection_id": Type.Optional(Type.String({"description":"collection_id parameter."})),"sort": Type.Optional(Type.Union([Type.Literal("relevance"),Type.Literal("delivery_time"),Type.Literal("rating"),Type.Literal("cost_low_to_high"),Type.Literal("cost_high_to_low")], {"description":"sort parameter."})),"offset": Type.Optional(Type.String({"description":"offset parameter."})),"tab": Type.Optional(Type.Union([Type.Literal("dish"),Type.Literal("restaurant")], {"description":"tab parameter."})),"veg": Type.Optional(Type.Boolean({"description":"veg parameter."})),"min_rating": Type.Optional(Type.Number({"description":"min_rating parameter."})),"offers": Type.Optional(Type.Boolean({"description":"offers parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"swiggy-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-swiggy.");
 }
 return register(api);
};
export default plugin;
