// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-espn",
 name: "Espn by Crawlora",
 description: "Public Espn data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_espn_news",description:"Use Crawlora to access public Espn data.",parameters:Type.Object({"sport": Type.Union([Type.Literal("football"),Type.Literal("basketball"),Type.Literal("baseball"),Type.Literal("hockey"),Type.Literal("soccer")], {"description":"sport parameter."}),"league": Type.Union([Type.Literal("nfl"),Type.Literal("college-football"),Type.Literal("nba"),Type.Literal("wnba"),Type.Literal("mens-college-basketball"),Type.Literal("womens-college-basketball"),Type.Literal("mlb"),Type.Literal("nhl"),Type.Literal("eng.1"),Type.Literal("esp.1"),Type.Literal("ita.1"),Type.Literal("ger.1"),Type.Literal("fra.1"),Type.Literal("usa.1"),Type.Literal("uefa.champions")], {"description":"league parameter."})}),async execute(params,config,context){return callCrawlora(config,context.signal,"espn-news",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-espn.");
 }
 return register(api);
};
export default plugin;
