// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-youtube",
 name: "YouTube by Crawlora",
 description: "YouTube video transcripts through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({
      name: "crawlora_youtube_transcript",
      description: "Fetch the transcript of a YouTube video.",
      parameters: Type.Object({
        id: Type.String({ description: "YouTube video id." })
      }),
      async execute(params, config, context) {
        return callCrawlora(config, context.signal, "youtube-transcript", params);
      }
    })],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-youtube.");
 }
 return register(api);
};
export default plugin;
