// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-github",
 name: "GitHub by Crawlora",
 description: "GitHub repository search through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_github_search_repositories",description:"Search public GitHub repositories.",parameters:Type.Object({"q": Type.String({"description":"Repository search query."}),"sort": Type.Optional(Type.Union([Type.Literal("stars"),Type.Literal("forks"),Type.Literal("help-wanted-issues"),Type.Literal("updated")], {"description":"Sort order."})),"order": Type.Optional(Type.Union([Type.Literal("asc"),Type.Literal("desc")], {"description":"Sort direction."})),"page": Type.Optional(Type.Integer({"description":"Page number.","minimum":1})),"per_page": Type.Optional(Type.Integer({"description":"Results per page.","minimum":1,"maximum":100}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"github-search-repositories",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-github.");
 }
 return register(api);
};
export default plugin;
