// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-justwatch",
 name: "Justwatch by Crawlora",
 description: "Public Justwatch data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_justwatch_discover",description:"Use Crawlora to access public Justwatch data.",parameters:Type.Object({"country": Type.Optional(Type.String({"description":"country parameter."})),"language": Type.Optional(Type.String({"description":"language parameter."})),"limit": Type.Optional(Type.Integer({"description":"limit parameter."})),"type": Type.Optional(Type.Union([Type.Literal("all"),Type.Literal("movie"),Type.Literal("show")], {"description":"type parameter."})),"genres": Type.Optional(Type.String({"description":"genres parameter."})),"providers": Type.Optional(Type.String({"description":"providers parameter."})),"production_countries": Type.Optional(Type.String({"description":"production_countries parameter."})),"monetization_types": Type.Optional(Type.Union([Type.Literal("FLATRATE"),Type.Literal("FREE"),Type.Literal("ADS"),Type.Literal("RENT"),Type.Literal("BUY")], {"description":"monetization_types parameter."})),"year_min": Type.Optional(Type.Integer({"description":"year_min parameter."})),"year_max": Type.Optional(Type.Integer({"description":"year_max parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"justwatch-discover",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-justwatch.");
 }
 return register(api);
};
export default plugin;
