// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-meta-jobs",
 name: "Meta Jobs by Crawlora",
 description: "Public Meta Jobs data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_meta_jobs_search",description:"Use Crawlora to access public Meta Jobs data.",parameters:Type.Object({"q": Type.Optional(Type.String({"description":"q parameter."})),"teams": Type.Optional(Type.String({"description":"teams parameter."})),"roles": Type.Optional(Type.String({"description":"roles parameter."})),"offices": Type.Optional(Type.String({"description":"offices parameter."})),"is_remote_only": Type.Optional(Type.Boolean({"description":"is_remote_only parameter."})),"sort_by_new": Type.Optional(Type.Boolean({"description":"sort_by_new parameter."})),"results_per_page": Type.Optional(Type.Union([Type.Literal("all"),Type.Literal("five"),Type.Literal("ten")], {"description":"results_per_page parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"meta-jobs-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-meta-jobs.");
 }
 return register(api);
};
export default plugin;
