// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-autotrader",
 name: "Autotrader by Crawlora",
 description: "Public Autotrader data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_autotrader_search",description:"Use Crawlora to access public Autotrader data.",parameters:Type.Object({"query": Type.Optional(Type.String({"description":"query parameter."})),"zip": Type.Optional(Type.String({"description":"zip parameter."})),"radius": Type.Optional(Type.Integer({"description":"radius parameter."})),"make": Type.Optional(Type.String({"description":"make parameter."})),"model": Type.Optional(Type.String({"description":"model parameter."})),"trim": Type.Optional(Type.String({"description":"trim parameter."})),"condition": Type.Optional(Type.Union([Type.Literal("new"),Type.Literal("used"),Type.Literal("certified"),Type.Literal("3p_cert")], {"description":"condition parameter."})),"body_style": Type.Optional(Type.Union([Type.Literal("convertible"),Type.Literal("coupe"),Type.Literal("hatchback"),Type.Literal("sedan"),Type.Literal("suv"),Type.Literal("truck"),Type.Literal("van"),Type.Literal("wagon")], {"description":"body_style parameter."})),"seller_type": Type.Optional(Type.Union([Type.Literal("dealer"),Type.Literal("private")], {"description":"seller_type parameter."})),"min_year": Type.Optional(Type.Integer({"description":"min_year parameter."})),"max_year": Type.Optional(Type.Integer({"description":"max_year parameter."})),"min_price": Type.Optional(Type.Integer({"description":"min_price parameter."})),"max_price": Type.Optional(Type.Integer({"description":"max_price parameter."})),"max_mileage": Type.Optional(Type.Integer({"description":"max_mileage parameter."})),"page": Type.Optional(Type.Integer({"description":"page parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"autotrader-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-autotrader.");
 }
 return register(api);
};
export default plugin;
