// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-hm",
 name: "Hm by Crawlora",
 description: "Public Hm data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_hm_listing",description:"Use Crawlora to access public Hm data.",parameters:Type.Object({"category_id": Type.String({"description":"category_id parameter."}),"page": Type.Optional(Type.Integer({"description":"page parameter."})),"page_size": Type.Optional(Type.Integer({"description":"page_size parameter."})),"sort": Type.Optional(Type.Union([Type.Literal("RELEVANCE"),Type.Literal("NEWEST_FIRST"),Type.Literal("PRICE_ASCENDING"),Type.Literal("PRICE_DESCENDING")], {"description":"sort parameter."})),"is_new": Type.Optional(Type.Boolean({"description":"is_new parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"hm-listing",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-hm.");
 }
 return register(api);
};
export default plugin;
