// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-boxofficemojo",
 name: "Boxofficemojo by Crawlora",
 description: "Public Boxofficemojo data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_boxofficemojo_brand",description:"Use Crawlora to access public Boxofficemojo data.",parameters:Type.Object({"id": Type.Optional(Type.String({"description":"id parameter."})),"path": Type.Optional(Type.String({"description":"path parameter."})),"url": Type.Optional(Type.String({"description":"url parameter."})),"sort": Type.Optional(Type.Union([Type.Literal("grossToDate"),Type.Literal("maxNumTheaters"),Type.Literal("openingWeekendGross"),Type.Literal("openingNumTheaters"),Type.Literal("releaseDate")], {"description":"sort parameter."})),"sortDir": Type.Optional(Type.Union([Type.Literal("asc"),Type.Literal("desc")], {"description":"sortDir parameter."})),"offset": Type.Optional(Type.Integer({"description":"offset parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"boxofficemojo-brand",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-boxofficemojo.");
 }
 return register(api);
};
export default plugin;
