// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-steam",
 name: "Steam by Crawlora",
 description: "Steam public app data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_steam_app",description:"Fetch public Steam app details.",parameters:Type.Object({"appid": Type.String({"description":"Steam application ID."}),"cc": Type.Optional(Type.String({"description":"Country code."})),"l": Type.Optional(Type.String({"description":"Language code."})),"filters": Type.Optional(Type.String({"description":"Optional response filters."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"steam-app",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-steam.");
 }
 return register(api);
};
export default plugin;
