// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-kalshi",
 name: "Kalshi by Crawlora",
 description: "Kalshi public event data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_kalshi_events",description:"List public Kalshi prediction events.",parameters:Type.Object({"limit": Type.Optional(Type.Number({"description":"Maximum events.","minimum":1,"maximum":1000})),"cursor": Type.Optional(Type.String({"description":"Pagination cursor."})),"series_ticker": Type.Optional(Type.String({"description":"Filter by series ticker."})),"category": Type.Optional(Type.String({"description":"Filter by category."})),"status": Type.Optional(Type.Union([Type.Literal("open"),Type.Literal("closed"),Type.Literal("settled")], {"description":"Event status."})),"with_nested_markets": Type.Optional(Type.Boolean({"description":"Include nested markets."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"kalshi-events",params);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-kalshi.");
 }
 return register(api);
};
export default plugin;
