// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-geocoding",
 name: "Geocoding by Crawlora",
 description: "Public Geocoding data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_geocoding_search",description:"Use Crawlora to access public Geocoding data.",parameters:Type.Object({"q": Type.Optional(Type.String({"description":"q parameter."})),"street": Type.Optional(Type.String({"description":"street parameter."})),"city": Type.Optional(Type.String({"description":"city parameter."})),"county": Type.Optional(Type.String({"description":"county parameter."})),"state": Type.Optional(Type.String({"description":"state parameter."})),"country": Type.Optional(Type.String({"description":"country parameter."})),"postalcode": Type.Optional(Type.String({"description":"postalcode parameter."})),"limit": Type.Optional(Type.Integer({"description":"limit parameter."})),"countrycodes": Type.Optional(Type.String({"description":"countrycodes parameter."})),"accept_language": Type.Optional(Type.String({"description":"accept_language parameter."})),"addressdetails": Type.Optional(Type.Boolean({"description":"addressdetails parameter."})),"extratags": Type.Optional(Type.Boolean({"description":"extratags parameter."})),"namedetails": Type.Optional(Type.Boolean({"description":"namedetails parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"geocoding-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-geocoding.");
 }
 return register(api);
};
export default plugin;
