// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-googlepatents",
 name: "Googlepatents by Crawlora",
 description: "Public Googlepatents data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_googlepatents_search",description:"Use Crawlora to access public Googlepatents data.",parameters:Type.Object({"q": Type.String({"description":"q parameter."}),"inventor": Type.Optional(Type.String({"description":"inventor parameter."})),"assignee": Type.Optional(Type.String({"description":"assignee parameter."})),"country": Type.Optional(Type.String({"description":"country parameter."})),"status": Type.Optional(Type.Union([Type.Literal("GRANT"),Type.Literal("APPLICATION")], {"description":"status parameter."})),"type": Type.Optional(Type.Union([Type.Literal("PATENT"),Type.Literal("DESIGN")], {"description":"type parameter."})),"language": Type.Optional(Type.Union([Type.Literal("ENGLISH"),Type.Literal("GERMAN"),Type.Literal("CHINESE"),Type.Literal("FRENCH"),Type.Literal("SPANISH"),Type.Literal("ARABIC"),Type.Literal("JAPANESE"),Type.Literal("KOREAN"),Type.Literal("PORTUGUESE"),Type.Literal("RUSSIAN"),Type.Literal("ITALIAN"),Type.Literal("DUTCH"),Type.Literal("SWEDISH"),Type.Literal("FINNISH"),Type.Literal("NORWEGIAN"),Type.Literal("DANISH")], {"description":"language parameter."})),"date_field": Type.Optional(Type.Union([Type.Literal("priority"),Type.Literal("filing"),Type.Literal("publication")], {"description":"date_field parameter."})),"before": Type.Optional(Type.String({"description":"before parameter."})),"after": Type.Optional(Type.String({"description":"after parameter."})),"sort": Type.Optional(Type.Union([Type.Literal("relevance"),Type.Literal("new"),Type.Literal("old")], {"description":"sort parameter."})),"num": Type.Optional(Type.Integer({"description":"num parameter."})),"page": Type.Optional(Type.Integer({"description":"page parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"googlepatents-search",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-googlepatents.");
 }
 return register(api);
};
export default plugin;
