// Generated by scripts/build-platforms.mjs; edit src/index.ts and scripts/platforms.mjs.
import { Type } from "typebox";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { callCrawlora } from "./client.js";
const plugin = defineToolPlugin({
 id: "crawlora-subway",
 name: "Subway by Crawlora",
 description: "Public Subway data through Crawlora.",
 configSchema: Type.Object({
    apiKey: Type.Optional(
      Type.String({
        description:
          "Crawlora API key. Falls back to the CRAWLORA_API_KEY environment variable."
      })
    )
  }),
 tools: (tool) => [tool({name:"crawlora_subway_nearby",description:"Use Crawlora to access public Subway data.",parameters:Type.Object({"latitude": Type.Optional(Type.Number({"description":"latitude parameter."})),"longitude": Type.Optional(Type.Number({"description":"longitude parameter."})),"query": Type.Optional(Type.String({"description":"query parameter."})),"store_id": Type.Optional(Type.String({"description":"store_id parameter."})),"limit": Type.Optional(Type.Integer({"description":"limit parameter."})),"offset": Type.Optional(Type.String({"description":"offset parameter."})),"features": Type.Optional(Type.String({"description":"features parameter."}))}),async execute(params,config,context){return callCrawlora(config,context.signal,"subway-nearby",params as Record<string, unknown>);}})],
});
const register = plugin.register;
plugin.register = (api) => {
 const umbrella = api.config?.plugins?.entries?.crawlora;
 if (umbrella && umbrella.enabled !== false) {
  throw new Error("Disable the Crawlora starter plugin first (openclaw plugins disable crawlora). Its tools overlap with crawlora-subway.");
 }
 return register(api);
};
export default plugin;
